- aeron-common/src/main/cpp/concurrent/AtomicBuffer.h
To avoid memory allocation when using this class as a wrapper over an underlying buffer it would be convenient to be able reposition the buffer which would be enabled with additional setters. 
Further, the getCapacity() is named after the Java implementation. Would it not be more correct to say getLength() or length() instead?
Thanks
> Additional getters and setters

- README.md
This helps diagnose why the samples might fail to run inside a Docker or in the situations when the sample programs are pointing to mismatched temporary directories, or if the temporary directory runs out of disk space.
> added troubleshooting and sample configuration doc

- aeron-client/src/main/java/uk/co/real_logic/aeron/Aeron.java
- aeron-client/src/main/java/uk/co/real_logic/aeron/FragmentAssemblyAdapter.java
- aeron-client/src/main/java/uk/co/real_logic/aeron/InactiveConnectionHandler.java
- aeron-client/src/main/java/uk/co/real_logic/aeron/NewConnectionHandler.java
- aeron-client/src/main/java/uk/co/real_logic/aeron/Publication.java
- aeron-client/src/main/java/uk/co/real_logic/aeron/Subscription.java
- aeron-common/src/main/java/uk/co/real_logic/aeron/common/CommonContext.java
- aeron-common/src/main/java/uk/co/real_logic/aeron/common/ErrorCode.java
- aeron-common/src/main/java/uk/co/real_logic/aeron/common/concurrent/logbuffer/BufferClaim.java
- aeron-common/src/main/java/uk/co/real_logic/aeron/common/concurrent/logbuffer/Header.java
- aeron-common/src/main/java/uk/co/real_logic/aeron/common/uri/AeronUri.java
- build.gradle
A trimmed down version of Javadoc for Aeron APIs. Two new tasks 'docs' and 'docsJar' have been added to the 'build.gradle'. In addition, more clarifications have been added to client APIs.
> A trimmed down version of Javadoc

- aeron-common/src/main/java/uk/co/real_logic/aeron/common/CommonContext.java
- aeron-system-tests/src/test/java/uk/co/real_logic/aeron/MultiDriverTest.java
Now appends a UUID to the base directory, and deletes the base directory on exit.
Avoids issues due to concurrent builds by different users on a shared system.
> Change the embedded driver directories to work better on multi-user systems. 

- aeron-common/src/main/java/uk/co/real_logic/aeron/common/NetworkUtil.java
- aeron-common/src/test/java/uk/co/real_logic/aeron/common/NetworkUtilTest.java
Corrected isMatchWithPrefix() to properly compare IPv6 addresses. Also corrected the corresponding unit test.
> Fix for IPv6 interface specification handling.

- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/Configuration.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/DriverConductor.java
Added a config property "aeron.driver.disable.naks", which, if set to true, will cause the media driver to effectively never send NAKs when it notices loss.  Useful for some types of automated testing.
> Ability to disable sending NAKs for testing

- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/Configuration.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/LossGenerator.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/RandomLossGenerator.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/UdpChannelTransport.java
- aeron-driver/src/test/java/uk/co/real_logic/aeron/driver/ReceiverTest.java
- aeron-driver/src/test/java/uk/co/real_logic/aeron/driver/SelectorAndTransportTest.java
- aeron-tools/src/main/java/uk/co/real_logic/aeron/tools/MediaDriverOptions.java
- aeron-tools/src/main/java/uk/co/real_logic/aeron/tools/MediaDriverTool.java
- aeron-tools/src/test/java/uk/co/real_logic/aeron/tools/MediaDriverOptionsTest.java
Added the receive buffer to the parameters passed to shouldDropFrame in the LossGenerator interface. This gives a test application much more information when deciding what to drop.
In order to use custom loss generators, I added the ability to provide an implementation through the MediaDriver Context. If one is provided, it will take precedence over the configured rate & seed random loss generator. The RandomLossGenerator and default behavior (no loss) work the same as before. 
Updated MediaDriverTool to create and use a LossGenerator specified on the command line.
> LossGenerator improvements

- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/media/UdpChannelTransport.java
Added some up-front checks for socket buffer sizes during MediaDriver startup rather than doing a per-socket check while creating new UdpChannelTransports.
Rather than throwing an exception when we're unable to set the desired size, we just accept the maximum the OS will give us.
Fixes #29
> Added socket buffer check during media driver startup

- aeron-client/src/main/java/uk/co/real_logic/aeron/Aeron.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/MediaDriver.java
Just makes the config code a little bit nicer for the users.
At the moment you have to do:
```Java
final Aeron.Context ctx = new Aeron.Context()
.errorHandler(aeronErrorHandler);
ctx.aeronDirectoryName(aeronDirectoryName);
```
Where this PR allows:
```Java
final Aeron.Context ctx = new Aeron.Context()
.aeronDirectoryName(aeronDirectoryName)
.errorHandler(aeronErrorHandler);
```
> Use covarient return types for aeronDirectoryName in Contexts.

- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/Configuration.java
- aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/DriverConductor.java
- aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/EmbeddedPingPong.java
- aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/raw/TransferToPing.java
- aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/raw/TransferToPong.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1192 - String literals should not be duplicated.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1192
Please let me know if you have any questions.
George Kankava
> squid:S1192 - String literals should not be duplicated

- aeron-client/src/main/cpp/util/MemoryMappedFile.h
The macros interfere with the std::min used in other parts of the code.
Compiler - VS 2013
> Hide the min/max macros defined in Windef.h

- aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/LogInspector.java
- aeron-samples/src/test/java/uk/co/real_logic/aeron/samples/LogInspectorAsciiFormatBytesTest.java
That seemed to me to be the intention in the previous code, however, the widening of the byte to an integer made sure that 'b' would never be negative and therefore the condition was redundant.
> fix formatting of bytes to ascii in LogInspector. Negative bytes to be formatted to zero

- aeron-client/src/main/java/io/aeron/Publication.java
- aeron-client/src/main/java/io/aeron/Subscription.java
Adds missing CLOSED return code to offer javadoc, and some minor spelling grammar fixes.
> Minor javadoc fixes

- CMakeLists.txt
These changes bump the CMake oldest version requirement to 3.0.2 in order to properly version the aeron project. The version is read from the `version.txt` file. CMake does not allow for a version suffix like `-SNAPSHOT`, so the suffix gets dropped. Regex expression used here does not limit number of version dot-components, but CMake may balk if there are more than three.
I have only ran the build on OS X 10.11.5 with XCode 7.3.1 and CMake 3.5.2.
> Project version in cmake

- aeron-client/src/main/cpp/Subscription.h
Changed passing these std::functions by reference, since with GCC 4.9.2 at least, passing by value resulted in a malloc/free, despite the fact that the closure was only capturing a 'this' pointer.
> [C++]: pass frag/block handler functions by reference in Subscription

- aeron-client/src/main/cpp/DriverProxy.h
It appears that clientId is not set on the flyweights for removeSubscription and removePublication sent to the driver. Doesn't seem to impact the functionality, however.
> [C++] Added setting clientId on remove messages to the driver

- aeron-agent/src/main/java/io/aeron/agent/ChannelEndpointInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/CleanupInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/CmdInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
Using Byte Buddy's Advice component, it is possible to inline code rather than adding additional methods that instrument via interceptor classes. This reduces the call stack depth, avoids allocations and ultimatively improves performance.
> aeron-agent: rather inline logging into methods than use delegation

- build.gradle
I would like to use the artifacts of this project in an OSGi environment. (Actually, they come in as transitive dependencies of the most recent akka-remote version.) So far, the produced jars do not contain any OSGi meta data.
This patch is pretty trivial. It just adds the Gradle OSGi plugin to the relevant projects. This produces standard OSGi meta data which is sufficient to use the jars as bundles in an OSGi container; I could verify that they could be deployed and used successfully in a local project.
> Make artifacts valid OSGi bundles.

- aeron-driver/src/main/cpp/media/InterfaceLookup.cpp
`BsdInterfaceLookup::lookupIPv4` and `BsdInterfaceLookup::lookupIPv6` can segfault on a machine with interfaces that have `NULL` `ifa_addr` (e.g. OpenVPN `tun` interface).
From the documentation of `getifaddrs`:
> `ifa_addr` and other fields can actually be `NULL` if the interface has no address, and no link-level address is returned if the interface has an IP address assigned.
> [C++]: Fixed segfault due to null ifa_addr from getifaddrs

- aeron-client/src/main/cpp/CMakeLists.txt
- aeron-client/src/main/cpp/concurrent/Atomic64.h
- aeron-client/src/main/cpp/concurrent/atomic/Atomic64_gcc_cpp11.h
I have tested this with the aeron-client tests using ctest and all tests pass. I have not done any heavy load testing, concurrency testing, etc.
> enable Aeron on non-x86-64 platforms with GCC and C++11 functions

- CMakeLists.txt
- aeron-client/src/main/cpp/ClientConductor.h
- aeron-client/src/main/cpp/util/Platform.h
- aeron-client/src/test/cpp/ClientConductorFixture.h
- aeron-samples/src/main/cpp/Ping.cpp
- aeron-samples/src/main/cpp/StreamingPublisher.cpp
- aeron-samples/src/main/cpp/Throughput.cpp
I have run `ctest` successfully on the Raspberry Pi (32-bit kernel/userland) without errors.
I do get intermittent test failures with the Java code when running `./gradelw`, which I believe is due to out-of-memory situations and an inability to consistently allocate memory-mapped buffers. I don't believe there's any underlying issue with the Java code.
> enable Aeron to run on 32-bit machines (tested w/ Raspberry Pi)

- aeron-client/src/main/cpp/util/MemoryMappedFile.cpp
- aeron-client/src/main/cpp/util/MemoryMappedFile.h
This allows files larger than 4GB to be mapped on Windows, and fixes a couple warnings that Visual Studio 2015 identifies.
> [C++] Improvements to file operations on Windows

- CMakeLists.txt
- aeron-client/src/main/cpp/Aeron.cpp
- aeron-client/src/main/cpp/ClientConductor.cpp
- aeron-client/src/main/cpp/ClientConductor.h
- aeron-client/src/main/cpp/CncFileDescriptor.h
- aeron-client/src/main/cpp/DriverProxy.h
- aeron-client/src/main/cpp/LogBuffers.cpp
- aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
- aeron-client/src/main/cpp/concurrent/broadcast/CopyBroadcastReceiver.h
- aeron-client/src/main/cpp/concurrent/logbuffer/DataFrameHeader.h
- aeron-client/src/main/cpp/concurrent/logbuffer/LogBufferDescriptor.h
- aeron-client/src/main/cpp/util/Index.h
This commit changes the internal time type to long long to be more compatible with 32-bit platforms and Windows 64-bit. It also brings it more in-line with Java, which uses the Java long type (equivalent to int64_t in C++).
This commit also fixes several warnings with type conversions from size_t to index_t (int32_t). There are also changes to handle certain cases where the size_t is out-of-range for the int32_t type.
> [C++] Change time to be long long and fix several warnings

- aeron-client/src/test/java/io/aeron/ClientConductorTest.java
Hello,
I am a graduate student at Oregon State University and as a part of my research and subject CS562 Applied Software Engineering project (Study and Refactoring of Functional Interface in Java), 
I have done refactoring of the Function<T,Integer> to ToIntFunction<T>.  
My project deals with the boxing and unboxing of Wrapper class and the primitive data-types. 
I want to know that whether the open source community is ready to accept these micro-optimizing refactorings or not. 
In the file ClientConductorTest, the Function<MutableDirectBuffer,Integer> is consumed as primitive int in the line **final int length = filler.apply(buffer)**.  So, Java Compiler has to autobox the Integer to int and because of that, the performance reduces. So, instead of using Function<T,Integer>, Java 8 has …
> Refactored the Function<T,Integer> to ToIntFunction<T>

- aeron-client/src/main/java/io/aeron/logbuffer/LogBufferDescriptor.java
A TermAppender fallen behind (ie in a past active partition), but that has already passed the backpressure check, could perform the claim when the tail is going to be reinitialised (ie the partition reactivated), hence the initialisation is needed to be atomic (a memory relaxed operation).
It is more likely to happen with a lot of producer threads (ie much more than the core count)and very small term capacity.
> [Java] Makes tail initialisation atomic

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
This is the small patch as discussed in gitter. Should be pretty straightforward, let me know if I've drifted from the code standards or something.
> [C]: Created macro condition for glibc<5.21 recvmmsg function signature

- aeron-client/src/main/cpp/Publication.h
- aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
- aeron-client/src/main/cpp/concurrent/logbuffer/TermAppender.h
- aeron-client/src/main/cpp/util/BitUtil.h
- aeron-client/src/test/cpp/concurrent/MockAtomicBuffer.h
- aeron-client/src/test/cpp/util/UtilTest.cpp
- aeron-driver/src/main/c/util/aeron_bitutil.h
I wanted the ability to offer multiple buffers and combine them into a single message. I noticed a similar issue had been brought up recently #(394), so I figured I would share what I've done. Comments are welcome.
> Added ability to offer a buffer range to a publication

- CMakeLists.txt
- aeron-client/src/main/cpp/ControlledFragmentAssembler.h
- aeron-client/src/main/cpp/FragmentAssembler.h
- aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
- aeron-client/src/main/cpp/concurrent/errors/DistinctErrorLog.h
- aeron-client/src/test/cpp/ExclusivePublicationTest.cpp
- aeron-client/src/test/cpp/PublicationTest.cpp
- aeron-client/src/test/cpp/concurrent/ConcurrentTest.cpp
- aeron-client/src/test/cpp/concurrent/ManyToOneRingBufferTest.cpp
- aeron-client/src/test/cpp/concurrent/MockAtomicBuffer.cpp
- aeron-client/src/test/cpp/concurrent/MockAtomicBuffer.h
- aeron-client/src/test/cpp/concurrent/OneToOneRingBufferTest.cpp
- aeron-client/src/test/cpp/concurrent/TermAppenderTest.cpp
- cppbuild/cppbuild
Concentrating on the C++ client and it's tests, i've tidied up various warnings from the windows build. The majority of these relate to 64->32 bit conversions which are warning on this build (but not with the osx/linux builds).
The build for me now builds the linux/osx client with only warnings from the included hdr_histogram project - i've submitted a pull to resolve those warnings with that which would allow the library to be warning free.
The most controversial change will probably be to the AtomicBuffer (and related Mock) where i've modified the length parameters to be size_t (so the constructor, capacity, wrap methods). I've left m_left data_type alone, and the corresponding get/set methods which take an offset, and the bounds checks still enforce that buffers fit within …
> [C++] Clear up various warnings on linux/windows, add support for warnings as error

- aeron-cluster/src/main/java/io/aeron/cluster/EgressPublisher.java
Sequencer gets stuck trying to inform clients that their session expired.
```
78454 observations from 2018-02-15 23:34:50.209+0000 to 2018-02-15 23:37:32.217+0000 for:
java.lang.IllegalStateException: Unexpected publication state: -1
at io.aeron.cluster.EgressPublisher.checkResult(EgressPublisher.java:105)
at io.aeron.cluster.EgressPublisher.sendEvent(EgressPublisher.java:60)
at io.aeron.cluster.SequencerAgent.checkSessions(SequencerAgent.java:845)
at io.aeron.cluster.SequencerAgent.slowTickCycle(SequencerAgent.java:662)
at io.aeron.cluster.SequencerAgent.doWork(SequencerAgent.java:261)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:233)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:159)
at java.lang.Thread.run(Unknown Source)
```
> Don't raise exception on cluster egress

- aeron-cluster/src/main/java/io/aeron/cluster/SequencerAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/RecordingLog.java
1. Fix bug in the RecoveryPlan where the wrong recording was fetched.
2. Adjust snapshot recovery so that if no log entry follows it, the correct logPosition is used for the new leadership term.
> Recovery from snapshot

- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredService.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
- aeron-cluster/src/test/java/io/aeron/cluster/StubClusteredService.java
onReplayEnd is not called when starting from clean state or recovering snapshot only.
> Notify ClusteredService that recovery has ended.

- aeron-cluster/src/main/java/io/aeron/cluster/SequencerAgent.java
When recovering multiple terms, validateServiceAck fails because currentTermPosition() returns the position from the previous term when it should return 0.
> Reset logAdapter when recovering

- aeron-cluster/src/main/java/io/aeron/cluster/client/RecordingLog.java
The ServiceContainer recording log doesn't store terms and leadershipTermId is different between restarts.
> Fix appendSnapshot test

- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
Previously, we were able to start a consensus module over a directory where old recordings had been deleted; however, upon upgrading to v1.9.0 this was no longer possible.
This change adds back the aforementioned behaviour. 
Inside `Catalog.refreshAndFixDescriptor(...)` it determines the maximum "segment index" for a given `recordingId` by looking at the file segments inside the archive directory. Previously it looked at all segment files. Now it just looks at the segment files that are for the `recordingId`.
> Allows Catalog to be constructed over a directory where old recordings have been deleted

- aeron-client/src/main/cpp/Context.h
gcc 8 introduced a new warning category `-Wcatch-value` enabled in `-Wall` that warns about catching a polymorphic class by value.
> Catch std::bad_cast by reference

- aeron-client/src/main/cpp/concurrent/AgentRunner.h
Hi, this is where I needed the thread name. Not sure if there are other places that need it, I only see this thread in my debugging.
Also I have a mac which uses a slightly different function to Linux. Not sure if there are other versions you want to support.
> Add thread names to c++

- aeron-client/src/main/cpp/DriverProxy.h
Semantically, there is no necessity for `std::function` as the call is not
stored nor type erasure is needed.
Furthermore, while compilers can optimize and inline the call, too complex
functions usually end up going through the `std::function` construction
and polymorphic call.
> Simplify local function call with compile time polymorphic semantics

- aeron-cluster/src/main/java/io/aeron/cluster/service/ClientSession.java
After disconnect(), if offer() was called on ClientSession, then dereferencing the responsePublication would cause a NullPointerException. This change adds a null-check in offer(), and will throw an IllegalStateException (with a descriptive message) instead.
> Improve exception message when ClientSession is used after disconnected

- aeron-client/src/main/cpp/Subscription.h
- aeron-client/src/main/java/io/aeron/Subscription.java
To be able to continue from the next `Image` in subsequent calls.
> Change the round-robin mechanism of Subscription's poll methods

- aeron-client/src/main/java/io/aeron/BufferBuilder.java
- aeron-client/src/main/java/io/aeron/BufferBuilderUtil.java
- aeron-client/src/test/java/io/aeron/BufferBuilderTest.java
- aeron-client/src/test/java/io/aeron/BufferBuilderUtilTest.java
Fixes an infinite loop when calculated `newCapacity` overflows:
```
final int newCapacity = Math.max(capacity + (capacity >> 1), MIN_ALLOCATED_CAPACITY);
// newCapacity is never negative, as Math.max returns MIN_ALLOCATED_CAPACITY
// when capacity + (capacity >> 1) overflows
if (newCapacity < 0 || newCapacity > MAX_CAPACITY)
```
Extracted utility method out to separate class to facilitate testing.
> [Java] Fix overflow issue when requesting large buffer size.

- aeron-client/src/main/cpp/util/MemoryMappedFile.cpp
- aeron-client/src/main/cpp/util/MemoryMappedFile.h
Makes sure 'off_t' is included before usage.
Fixes #544
> Moved include of <sys/types.h> from cpp to header

- CMakeLists.txt
- aeron-client/src/main/cpp/util/Exceptions.h
- aeron-client/src/test/cpp/util/TestUtils.h
- aeron-client/src/test/cpp/util/UtilTest.cpp
- aeron-driver/src/main/c/aeron_agent.c
- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_receiver.c
- aeron-driver/src/main/c/aeron_driver_sender.c
- aeron-driver/src/main/c/aeron_system_counters.c
- aeron-driver/src/main/c/collections/aeron_str_to_ptr_hash_map.h
- aeron-driver/src/main/c/concurrent/aeron_broadcast_transmitter.c
- aeron-driver/src/main/c/concurrent/aeron_counters_manager.c
- aeron-driver/src/main/c/concurrent/aeron_distinct_error_log.c
- aeron-driver/src/main/c/concurrent/aeron_mpsc_rb.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
- aeron-driver/src/main/c/util/aeron_fileutil.c
Today, SourcedException uses the absolute path of wherever aeron was built. I'd instead like it to refer to the relative path within the source tree.
It's probably misleading for a potential production exception to refer to /home/luke/aeron... or something to that effect.
> Use relative path in SourcedException

- aeron-client/src/main/cpp/util/StringUtil.h
Fixes #562 (which addresses a `clang --analyze` static code check failure).
> Initialise variable (in case std::cin is closed or otherwise read from it fails)

- .travis.yml
- README.md
I've added configuration for travis builds covering linux and OSX.
If accepted, the maintainers have to press a button at https://travis-ci.org to activate.
This change is motivated because in #560 I apparently created a build issue that I can't reproduce.
Incidentally, I find that OSX builds currently fail on io.aeron.MemoryOrderingTest. I've marked OSX as allowed to fail in the submission for now.
> Add CI builds

- CMakeLists.txt
- aeron-client/src/main/cpp/CMakeLists.txt
- aeron-client/src/main/cpp/ExclusivePublication.h
- aeron-client/src/main/cpp/Subscription.h
- aeron-client/src/test/cpp/concurrent/OneToOneRingBufferTest.cpp
- aeron-driver/src/main/c/CMakeLists.txt
- aeron-driver/src/test/c/aeron_spsc_rb_test.cpp
- aeron-samples/src/main/cpp/CMakeLists.txt
Continuation of the earlier work on making Aeron more modular when added as a subproject, making documentation and installation optional. Behaviour is not affected when Aeron is built as a standalone project.
> Modular build and copy paste fixes

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterSession.java
- aeron-cluster/src/main/java/io/aeron/cluster/EgressPublisher.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClientSession.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
A channel that was resolvable at connection time can subsequently become unresolvable which causes a cascade of errors when a node becomes leader or the cluster is coming up after shutdown.
```
io.aeron.exceptions.RegistrationException: errorCodeValue=1 java.net.UnknownHostException: could not resolve endpoint address: xxx.host:9020
at io.aeron.ClientConductor.onError(ClientConductor.java:169)
at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:85)
at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:120)
at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:56)
at io.aeron.ClientConductor.service(ClientConductor.java:718)
at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:762)
at …
```
> Treat Egress Channel as NOT_CONNECTED on InvalidChannelException

- README.md
LGTM parses GitHub repository names in a case-sensitive way.
> Fix LGTM links

- CMakeLists.txt
- aeron-client/src/main/cpp/util/Exceptions.h
- aeron-client/src/test/cpp/util/TestUtils.h
- aeron-client/src/test/cpp/util/UtilTest.cpp
Have sourced exceptions contain text that looks like aeron-client/.../filename instead of /home/luke/aeron/aeron-client....
Note that #555 was a previous attempt at this.
> Use relative source path in exceptions

- aeron-cluster/src/test/java/io/aeron/cluster/StartClusterFromTruncatedRecordingLogTest.java
Adds an integration test that demonstrates that the cluster is able to start from valid post-snapshot state, when no-longer-required recording log entries have been purged.
> Add test to demonstrate pruning entries from the recording log

- CMakeLists.txt
- aeron-client/src/main/cpp/CMakeLists.txt
- aeron-driver/src/test/c/CMakeLists.txt
This is required in case there is an upper level directory that includes
Aeron. In that case the added definitions do not reach the source files
that may include Aeron headers and __PROJECT_SOURCE_DIR__ will be
undefined to them.
> [C++] Add definition for __PROJECT_SOURCE_DIR__ to aeron_client's public interface

- CMakeLists.txt
`c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old …
> Fix 'extended alignment' error in Visual Studio 2017 (>15.8)

- aeron-client/src/main/cpp/util/Exceptions.h
As per discussion https://github.com/real-logic/aeron/pull/596
> Macro guard against missing _PROJECT_SOURCE_DIR_

- aeron-system-tests/src/test/java/io/aeron/StartStopSystemTest.java
that's because io.aeron.driver.MediaDriver.Context#close unmaps cnc and lossReoprt buffers.
But the media driver tries to write some counter value to the cnc.
> Segv in #612 is still an issue

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterSession.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClientSession.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
Use shared egress publication in ClusteredService. CM already ensures the Publication is connected as part of the session processing logic.
Sharing this publication reduces the likelyhood of having to block the service thread. 
e.g. if a message needs to be sent as a result of onSessionOpen.
> Share egress publication between CM & CSC

- aeron-client/src/main/cpp/Aeron.h
- aeron-client/src/main/cpp/BufferBuilder.h
- aeron-client/src/main/cpp/CMakeLists.txt
- aeron-client/src/main/cpp/ClientConductor.h
- aeron-client/src/main/cpp/Context.h
- aeron-client/src/main/cpp/ControlledFragmentAssembler.h
- aeron-client/src/main/cpp/Counter.h
- aeron-client/src/main/cpp/ExclusivePublication.cpp
- aeron-client/src/main/cpp/ExclusivePublication.h
- aeron-client/src/main/cpp/FragmentAssembler.h
- aeron-client/src/main/cpp/Image.h
- aeron-client/src/main/cpp/LogBuffers.h
- aeron-client/src/main/cpp/Publication.cpp
- aeron-client/src/main/cpp/Publication.h
- aeron-client/src/main/cpp/Subscription.h
- aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
- aeron-client/src/main/cpp/concurrent/AtomicCounter.h
- aeron-client/src/main/cpp/concurrent/logbuffer/Header.h
- aeron-client/src/main/cpp/concurrent/status/UnsafeBufferPosition.h
- aeron-client/src/main/cpp/util/BitUtil.h
- aeron-client/src/main/cpp/util/CommandOption.cpp
- aeron-client/src/main/cpp/util/CommandOption.h
- aeron-client/src/main/cpp/util/LangUtil.h
- aeron-client/src/main/cpp/util/StringUtil.h
- aeron-driver/src/main/c/util/aeron_bitutil.h
And two new features:
* Make Image movable without a copy.
* Add an accessor to Context for media driver timeout.
> Various cleanup of C++ client

- aeron-archive/src/main/java/io/aeron/archive/client/ControlResponsePoller.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java
When spawning clients simultaneously the following exception is thrown in some of the clients:
```
io.aeron.exceptions.TimeoutException: awaiting response - correlationId=24
at io.aeron.archive.client.AeronArchive.checkDeadline(AeronArchive.java:1008)
at io.aeron.archive.client.AeronArchive.pollNextResponse(AeronArchive.java:1122)
at io.aeron.archive.client.AeronArchive.awaitSessionOpened(AeronArchive.java:1021)
at io.aeron.archive.client.AeronArchive.<init>(AeronArchive.java:109)
at io.aeron.archive.client.AeronArchive.connect(AeronArchive.java:183)
at io.aeron.archive.ArchiveTest.lambda$shouldAllowMultipleConnectionsInParallel$0(ArchiveTest.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at …
```
> [Java] Fix issue where multiple archive clients are trying to connect.

- aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestMessages.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestNode.java
This test captures some behaviour we've seen at a client. 
Please let me know if you'd like me to clean it up at all. I considered injecting a different `ClusteredService` implementation rather than adding the switching in the existing one. I'm not sure what your preference is.
We see follower nodes stuck whilst catching up after performing the following steps:
1. Starting a 3 node cluster
2. Stopping a follower node
3. Sending a message to the cluster that triggers a timer to be
registered
4. Starting the follower node (again)
I've added two tests:
- `shouldCatchUpAfterFollowerMissesAMessage()` passes; but
- `shouldCatchUpAfterFollowerMissesTimerRegistration()` fails
The only difference between them is that the failing one registers a timer in the `onSessionMessage(...)` handler of …
> [Java] Test showing recovery issue with timers.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
Fix bug which dropped a session if its opening was the last event to be appended to the log before an election.
> [Java] Fix bug when truncating sessions before election.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
Use of the `Predicate` was causing the `long` values to be auto-boxed to `Long`.
> [Java] Remove source of garbage when cancelling missed timers

- aeron-driver/src/main/java/io/aeron/driver/PublicationImage.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationSubscriptionTest.java
Driver was throwing the following exception:
```
java.lang.ArrayIndexOutOfBoundsException: 1
at io.aeron.driver.PublicationImage.trackConnection(PublicationImage.java:802)
at io.aeron.driver.PublicationImage.addDestinationConnectionIfUnknown(PublicationImage.java:416)
at io.aeron.driver.DataPacketDispatcher.onSetupMessage(DataPacketDispatcher.java:325)
at io.aeron.driver.media.ReceiveChannelEndpoint.onSetupMessage(ReceiveChannelEndpoint.java:369)
at io.aeron.driver.media.DataTransportPoller.poll(DataTransportPoller.java:175)
at io.aeron.driver.media.DataTransportPoller.pollTransports(DataTransportPoller.java:78)
at io.aeron.driver.Receiver.doWork(Receiver.java:72)
at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
at …
```
> Fix bug with multi-destination subscription where destinations are setup in advance.

- aeron-samples/src/main/java/io/aeron/samples/BacklogStat.java
Regard to discussion in #482 I wrote my understanding how streamStats work down to the code. 
Output of this tool looks like:
```
sessionId=508185878 streamId=10 channel=aeron:udp?endpoint=localhost:40123 : 
┌─for publisher 5 the last known position is 60069504 (~8416768 bytes before a back-pressure)
└─sender 5 is up to position 60097856 (103872 bytes the sender may send up to ASAP.)
┌─receiver 7 is up to position 60097664
└─subscriber 2 has 0 bytes in backlog
sessionId=508185877 streamId=10 channel=aeron:udp?endpoint=localhost:40124 : 
┌─for publisher 4 the last known position is 60069568 (~8416704 bytes before a back-pressure)
└─sender 4 is up to position 60097856 (101888 bytes the sender may send up to ASAP.)
┌─receiver 6 is up to position 60097664
└─subscriber 3 has 0 bytes in backlog …
```
> Subscriber backlog tool 

- build.gradle
- gradle/build-scans.gradle
This small PR configures the `build-scan` Gradle plugin (https://guides.gradle.org/creating-build-scans/) which yields further insight into the build, allowing the team to make informed decisions on where and when the build may be tweaked to get faster, more performant builds.
Here's an example scan https://scans.gradle.com/s/jkf57dj4qsrrq
> Configure build-scan plugin

- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
The senderBpe AtomicCounter is not being closed when
NetworkPublication::close is being invoked. This is causing a small
resource leak in the MediaDriver
> [Tom/Michael/Andrey] Close NetworkPublication::senderBpe

- aeron-archive/src/main/java/io/aeron/archive/CatalogTool.java
- aeron-archive/src/main/java/io/aeron/archive/RecordingReader.java
hi! I really miss that feature to take a look on the data are stored by archive. 
the output looks like this
```
INFO: Mark file exists: /tmp/archive-test/archive-mark.dat
03:36:57 (start: 2019-05-17 03:36:48, activity: 2019-05-17 03:36:48)
[MarkFileHeader](sbeTemplateId=200|sbeSchemaId=100|sbeSchemaVersion=0|sbeBlockLength=128):version=257|activityTimestamp=1558053408638|startTimestamp=1558053408413|pid=5237|controlStreamId=10|localControlStreamId=11|eventsStreamId=30|controlChannel='aeron:udp?endpoint=localhost:8010'|localControlChannel='aeron:ipc'|eventsChannel='aeron:udp?control-mode=dynamic|control=localhost:8030'|aeronDirectory='/dev/shm/aeron-ivan'
Catalog Max Entries: 8192
Verbose mode is on. We will print 9223372036854775807 fragments at a time.
Recording 0 
channel: aeron:ipc …
```
> add new verbose option in the CatalogTool

- aeron-cluster/src/main/java/io/aeron/cluster/TimerService.java
Fix a bug in which timer correlation id is lost in case of log append backpressure.
> Retain timer on log append backpressure

- aeron-archive/src/main/java/io/aeron/archive/client/AeronArchive.java
It's the last place where no setting the given error handler in a context `conclude`. And by default Aeron has a little dangerous handler with `System.exit` in the timeout case.
> [Java] Use AeronArchive error handler in `conclude` if any

- build.gradle
This change moves to using the biz.aQute.bnd Gradle plugin to
produce OSGi-compatible manifests in jar files. Currently, only the
aeron-client, aeron-driver, and aeron-cluster modules have been updated
to provide OSGi metadata because the other modules are samples, tests,
or should never need to be visible inside an OSGi container. Care
has been taken to preserve the existing defined manifest fields
(Automatic-Module-Name, Implementation-Title, etc).
Note that until Agrona 1.0.4 is released (or at least a version containing
https://github.com/real-logic/agrona/commit/49e769e07c3ba3fa176d3b1079f2472184612e1d),
the generated package imports for Agrona will be unversioned. This will
self-correct when Agrona 1.0.4+ is released and Aeron is updated to
point to the new version.
> Add OSGi manifest headers

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
The cursor to select the next member status endpoint currently gets stuck at the last array position. This change causes the cursor to be reset along with other state in the ClusterBackupAgent.
> [Java] Ensure that clusterMembersStatusEndpointsCursor is reset

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
This change explicitly stops a live log recording when the ClusterBackupAgent is closed
> [Java] Explicitly stop live log backup

- aeron-archive/src/main/java/io/aeron/archive/ArchivingMediaDriver.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusteredMediaDriver.java
Avoid resource leaks in situations like:
```
java.nio.file.FileSystemException: aeron-archive\23-0.rec: The process cannot access the file because it is being used by another process.
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
at java.base/java.nio.file.Files.delete(Files.java:1141)
at org.agrona.IoUtil.delete(IoUtil.java:156)
at org.agrona.IoUtil.delete(IoUtil.java:147)
at …
```
> [Java] Prevent resource leak in case of failed launch.

- aeron-client/src/main/cpp/ClientConductor.cpp
- aeron-client/src/main/cpp/ClientConductor.h
- aeron-client/src/main/cpp/ExclusivePublication.cpp
- aeron-client/src/main/cpp/ExclusivePublication.h
- aeron-client/src/test/cpp/ExclusivePublicationTest.cpp
As exclusive publications are guaranteed to be original.
> [C++] Remove original registration ID from ExclusivePublication.

- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
Simplify calculation of stopPosition when fixing Archive catalog. Add assertions in test to remove possibility of silent failures.
> [Java] Simplify calculation of stopPosition

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/test/java/io/aeron/cluster/DynamicMembershipTest.java
There is an null pointer issue in next case:
1. Start 3 static nodes.
2. Join 1 dynamic node.
3. Stop LEADER.
Result: NullPointerException in other static nodes with next exception
```
E 2019-10-29T13:56:20,473 i.s.a.ClusteredServiceRunner Exception occurred at ConsensusModule:  [consensus-module]
java.lang.NullPointerException: null
at io.aeron.cluster.MemberStatusPublisher.canvassPosition(MemberStatusPublisher.java:60) ~[aeron-cluster-1.23.1-SNAPSHOT.jar:1.23.1-SNAPSHOT]
at io.aeron.cluster.Election.canvass(Election.java:508) ~[aeron-cluster-1.23.1-SNAPSHOT.jar:1.23.1-SNAPSHOT]
at io.aeron.cluster.Election.doWork(Election.java:205) [aeron-cluster-1.23.1-SNAPSHOT.jar:1.23.1-SNAPSHOT]
at io.aeron.cluster.ConsensusModuleAgent.doWork(ConsensusModuleAgent.java:295) …
```
> [Java] Fix NullPointerException when dynamic node joined and leader disappear

- aeron-client/src/main/cpp/ClientConductor.cpp
- aeron-client/src/main/cpp/Subscription.h
- aeron-client/src/main/cpp/concurrent/AtomicArrayUpdater.h
MSCV is correctly complaining about the narrowing conversion from
`std::size_t` to `int` in `AtomicArrayUpdater::removeElement`.
This patch makes us return a `std::size_t` instead. Using `-1` to
signify an invalid length is not needed as the length value is not used
anyway if the pointer is null. Hence we use `0` as the invalid value and
avoid the narrowing conversion.
> [C++] Fix narrowing conversion in client

- aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java
`entriesCache` was written out twice in the `toString` method. Inferring the correct field to be `cacheIndexByLeadershipTermIdMap`...
> [Java] use correct field in `toString` method of `RecordingLog`

- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
Send `leadershipTermId` along with `SessionCloseRequest` since it is used in `onSessionClose` method of `ConsensusModuleAgent` to check if session has to be closed on the cluster side:
https://github.com/real-logic/aeron/blob/17fc41b01ef292e61640ff57ad1275a7ae271e36/aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java#L349-L361
> [Java] Send `leadershipTermId` in `SessionCloseRequest`

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java
Because the 'id' field is not set for these, they clash with "Bytes Sent" when read (id=0).
Simplest strategy seemed to be to give them their own types.
> Error Counter Type IDs

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestNode.java
https://github.com/real-logic/aeron/blob/68fa2ea29f329e88acdc1d82039f2e09ef4246cc/aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java#L844
This check returns true after the Aeron portion of the snapshot, which means the user portion may or may not be transferred.
I've submitted a quick fix to check EoS but wanted to discuss more complete solutions. 
Two options I can see are:
- Query remote recording stop position when transferring snapshot and use that as the threshold condition for 'done'.
- Use Archive replicate functionality.
Any thoughts?
> Snapshots are not completely transferred by ClusterBackupAgent

- aeron-system-tests/src/test/java/io/aeron/BufferClaimMessageTest.java
- aeron-system-tests/src/test/java/io/aeron/ChannelEndpointStatusTest.java
- aeron-system-tests/src/test/java/io/aeron/ControlledMessageTest.java
- aeron-system-tests/src/test/java/io/aeron/CounterTest.java
- aeron-system-tests/src/test/java/io/aeron/ExclusivePublicationTest.java
- aeron-system-tests/src/test/java/io/aeron/FlowControlStrategiesTest.java
- aeron-system-tests/src/test/java/io/aeron/FragmentedMessageTest.java
- aeron-system-tests/src/test/java/io/aeron/ImageAvailabilityTest.java
- aeron-system-tests/src/test/java/io/aeron/MaxPositionPublicationTest.java
- aeron-system-tests/src/test/java/io/aeron/MemoryOrderingTest.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationSubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/PongTest.java
- aeron-system-tests/src/test/java/io/aeron/PublicationUnblockTest.java
- aeron-system-tests/src/test/java/io/aeron/PublishFromArbitraryPositionTest.java
- aeron-system-tests/src/test/java/io/aeron/ReentrantClientTest.java
- aeron-system-tests/src/test/java/io/aeron/SessionSpecificPublicationTest.java
- aeron-system-tests/src/test/java/io/aeron/SpySimulatedConnectionTest.java
- aeron-system-tests/src/test/java/io/aeron/SpySubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/TermBufferLengthTest.java
- aeron-system-tests/src/test/java/io/aeron/TwoBufferOfferMessageTest.java
- aeron-system-tests/src/test/java/io/aeron/UntetheredSubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/support/CTestMediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/support/DriverOutputConsumer.java
- aeron-system-tests/src/test/java/io/aeron/support/JavaTestMediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/support/MediaDriverTestWatcher.java
- aeron-system-tests/src/test/java/io/aeron/support/NativeTestMediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/support/TestMediaDriver.java
- build.gradle
This allows for the system tests to be run against a C Media Driver.  This is achieved by setting the `aeron.test.system.aeronmd.path` system property to be the location of a C Media Driver binary.
To make a new test work against the C Media Driver, use the `TestMediaDriver::launch` method.  It will default to the Java one and automatically flip to the C version when the property is set.
If the test fails and you need to get at the stdout/stderr information from the C Media Driver process, Add `@Rule public MediaDriverTestWatcher watcher = new MediaDriverTestWatcher();` to the test and pass the `watcher` into the `TestMediaDriver::launch` method as the second argument.  The `FlowControlStrategiesTest` shows this in use.
If a test uses a feature that is not supported, use …
> Media driver agnostic system tests

- .gitignore
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/GapFillLossTest.java
- aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java
- aeron-system-tests/src/test/java/io/aeron/test/LossReportTestUtil.java
Move over to using the LossReportReader instead.  Will be necessary for testing the C media driver.
> Remove uses of mocked LossReport to test loss in system tests.

- build.gradle
Hello
This commit fixes a couple of faults in the incremental and parallel builds of this project.
First, it makes the time-consuming task `generateCodecs` incremental.
Second, it fixes a race condition related to the creation of the sources Jar. In particular, `sourcesJar` must be executed after the task `generateCodecs`. Otherwise, the created jar does not include the files generated by this task.
These are the files that are missing when `sourcesJar` runs before `generateCodecs`:
```
< io/aeron/cluster/codecs/
< io/aeron/cluster/codecs/SessionCloseRequestDecoder.java
< io/aeron/cluster/codecs/ClientSessionEncoder.java
< io/aeron/cluster/codecs/ChallengeResponseEncoder.java
< io/aeron/cluster/codecs/ElectionStartEventDecoder.java
< io/aeron/cluster/codecs/ClusterAction.java
< …
```
> Fix faults in incremental and parallel builds

- aeron-system-tests/src/test/java/io/aeron/GapFillLossTest.java
- aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java
- aeron-system-tests/src/test/java/io/aeron/test/CTestMediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/test/JavaTestMediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/test/TestMediaDriver.java
When running the system tests.  Still requires the setting of the system properties to enable the C driver to run, so can be committed at any point.  To actually run the loss based system tests against the C driver requires PR #760.
I've used a slightly hacky approach to track the configuration for the loss generation on the C driver side, mainly because the loss generation information on the MediaDriver.Context is not declarative.  I've gone for the approach requiring the smallest amount of work.  There may be scope for something DSL to set up the media drivers instead of using the Context.
> Allow configuration of the loss generating transport binding for the C media driver.

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.h
- aeron-driver/src/test/c/media/aeron_udp_channel_transport_loss_test.cpp
Adds an inner struct to track meta information (name, type, source_symbol, next_binding) that can be useful when printing out the binding configuration.  Currently this happens in the `print_configuration` function in the driver.  Output will look something like:
```
udp_channel_transport_bindings.interceptor=loss,0x7f13fee9539f(/home/mike/sources/aeron/aeron-native/cmake-build-debug/lib/libaeron_driver.so:aeron_udp_channel_transport_loss_load)
udp_channel_transport_bindings.media=default,0x7f13feea93e0(/home/mike/sources/aeron/aeron-native/cmake-build-debug/lib/libaeron_driver.so:aeron_udp_channel_transport_bindings_default)
```
Where the order printed is the order that the bindings are applied, so there could be multiple `udp_channel_transport_bindings.interceptor` lines.
> Meta info on bindings

- aeron-client/src/main/java/io/aeron/Aeron.java
Could we print a timestamp along with stacktraces to help cross-reference them against an application's log file?  I haven't formatted the timestamp to keep it simple and avoid garbage.  It's using synchronized on System.err to keep the logging together.  It's going to take a synchronized lock on it in printStackTrace() anyway.
> [Java] Print timestamp with stacktraces in DEFAULT_ERROR_HANDLER

- aeron-client/src/main/java/io/aeron/Aeron.java
A recent change made the default `ErrorHandler` synchronize on `System.err` while calling `System.exit`. Any shutdown hook registered with the JVM that attempted to write to `System.err` could produce a deadlock.
This change applies the synchronization block to the logging only.
> [Java] Reduce the chance of deadlock when shutdown hook writes to `System.err`

- aeron-client/src/main/java/io/aeron/Aeron.java
Enforce `DEFAULT_ERROR_HANDLER` to print stacktrace to the same `System.err` instance upon which synchronization is performed.
> [Java] Enforce stacktrace printing to `System.err`

- aeron-driver/src/main/c/CMakeLists.txt
Fix for #779 (cmake will stop with fatal error if both poll and epoll are missing)
> [C] Media driver build should fail if neither POLL nor EPOLL is supported

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolVerifyTests.java
Also validate the following invariants:
- `startPosition >= 0`
- `startPosition <= stopPosition` if `stopPosition != NULL_POSITION`
- `startPosition <= stopPosition <= maxPosition`, where `maxPosition` is computed from the max segment file name plus segment file size
> [Java] Recover stopPosition when startPosition is non-zero

- aeron-client/src/main/java/io/aeron/Image.java
it might be a case when an image is end of stream but if you print out the image statistic (toStirng() method) you see
```
isEos=false
```
> [Java] improve Image toString() information

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolVerifyTests.java
Changes in this PR:
- Use start `termOffset` when computing position or validating the initial segment file
- Additional validation for start/stop position
- Re-written tests to reflect actual use-cases
> Stop position recovery

- aeron-driver/src/main/c/aeron_windows.c
- aeron-driver/src/main/c/util/aeron_error.c
- aeron-driver/src/main/c/util/aeron_error.h
This is the change discussed [here](https://github.com/real-logic/aeron/pull/789#discussion_r360052814). When the C media driver is used as a DLL, the TLS slot used to handle the error state is now managed by `DllMain`, and the per-thread memory is correctly freed when a thread exits.
> [C] Handle error TLS from DllMain

- build.gradle
In Gradle `compile` and `testCompile` dependency scopes were deprecated and will be removed in Gradle 7.0. They need to migrated to `implementation` or `api` for `compile` and `testImplementation` for `testCompile`.
**_Note: changing from `compile` to `implementation` makes a dependency non-transitive._**
See [API and implementation separation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation).
> [Java] Remove 'compile' and 'testCompile' scope dependencies from Gradle build

- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/ChannelEndpointInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/CmdInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/ControlInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/EventConfiguration.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventCodeTest.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventLoggerTest.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveLoggingAgentTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventCodeTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterLoggingAgentTest.java
- aeron-agent/src/test/java/io/aeron/agent/Common.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventCodeTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverLoggingAgentTest.java
- aeron-agent/src/test/java/io/aeron/agent/EventConfigurationTest.java
- aeron-archive/src/main/java/io/aeron/archive/ControlResponseProxy.java
- Conditionally weave based on the enabled events where possible, i.e. where mapping is one to one. In other cases keep runtime check to not log what was not configured to be logged.
- Add logging event for `io.aeron.archive.ControlResponseProxy#sendResponseHook`.
- Implement proper de-instumentation to allow testing different event combinations
- Switch to `EnumSet` for enabled events, i.e. lift 63 events per category limitation.
Open points:
- Should `io.aeron.agent.EventConfiguration#EVENT_RING_BUFFER` be re-created upon `init`.
> [Java] Agent fine grained weaving

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/RecordingLogTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
The intention of this patch is to allow tombstoned snapshots to be restored correctly when being replayed.  To make this work.
1. The RecordingLog does not remove tombstoned entries from its caches when `tombstoneEntry` is called.  Instead it marks the entry, but keeps it in the `entryCache`.  It is removed from the `cacheIndexByLeadershipTermIdMap` if applicable.
1. The on-disk state is updated to flip the top bit of the type id field to indicate that the entry is invalid.  This is to allow compatibility with the existing RecordingLog on disk format.
1. The ClusterMarkFile version is bumped to 0.1.0.
1. When the RecordingLog is loaded or a snapshot is tombstoned, the index of the invalid snapshot is added to the `invalidSnapshots` list.
1. When the `appendSnapshot` is called, it will …
> Tombstoned snapshots

- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/CommonEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventLogger.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventLoggerTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventEncoderTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventLoggerTest.java
- aeron-agent/src/test/java/io/aeron/agent/Common.java
- aeron-agent/src/test/java/io/aeron/agent/CommonEventEncoderTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventEncoderTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventLoggerTest.java
Replace write/offer into the ring buffer with the `tryClaim` call which has the following benefits:
- Zero-copy logging since no intermediate buffers need to be created
- Zero-overhead logging when buffer is full, i.e. now the space is claimed first before the message is encoded whereas previously the message was encoded but then offer might have failed meaning that work would have been wasted
_**NOTE: This PR requires `agrona-1.3.0` so the build will fail until Agrona is released and integrated into Aeron.**_
> [Java] Use `RingBuffer#tryClaim` API to implement zero-copy logging

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterNodeControlProperties.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterToolTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
Adds support for snapshot, suspend, resume, shutdown and abort to ClusterTool.  Will only apply the actions if the cluster is in the right state and the toggle is in NEUTRAL.  I.e. it will only apply to master.  Will error out with a useful message (and a non-zero exit code) if the necessary preconditions are not met.
> Clustertool commands

- aeron-archive/src/main/java/io/aeron/archive/ReplaySession.java
- aeron-archive/src/test/java/io/aeron/archive/ReplaySessionTest.java
- aeron-client/src/main/java/io/aeron/ExclusivePublication.java
- aeron-client/src/main/java/io/aeron/logbuffer/ExclusiveTermAppender.java
- aeron-client/src/test/java/io/aeron/logbuffer/ExclusiveTermAppenderTest.java
- aeron-system-tests/src/test/java/io/aeron/ExclusivePublicationTest.java
In order to apply some batching for the replay a new method `ExclusivePublication#offerBlock` was added. It is a low-level API intended for offering pre-formatted block of messages directly into publication. This method then copies provided block verbatim into the underlying term.
Preliminary performance tests showed a 50% increase in message throughput for the replay.
> [Java] Re-implement replay using new `offerBlock` API

- aeron-client/src/main/java/io/aeron/Aeron.java
- aeron-client/src/main/java/io/aeron/CommonContext.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
Basic implementation, intended for discussion.
Set aeron.debug.timeout.ns to some value.  For timeouts that need to be overridden, it calls `CommonContext::checkDebugTimeout` and replaces them with this value (if the debugger is attached).  It prints out a message to `stdout` when this occurs.  I didn't cover all of the timeouts, but enough that it allowed me to debug a couple of the cluster tests.
> [Java] Increase timeouts when running in debug.

- aeron-driver/src/main/java/io/aeron/driver/TaggedMulticastFlowControl.java
- aeron-driver/src/test/java/io/aeron/driver/DefaultMulticastFlowControlSupplierTest.java
- aeron-driver/src/test/java/io/aeron/driver/TaggedMulticastFlowControlTest.java
- aeron-system-tests/src/test/java/io/aeron/UriSpecifiedFlowControlTest.java
- Parses the group size value from the URI.
- Follows the same strict rules applied to the C driver (relies on StringIndexOutOfBounds, IllegalArgumentException for error handling).
- Adds system property configurable default for the required group size.
> Parsing required group size from URI

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_flow_control.c
- aeron-driver/src/main/c/aeron_flow_control.h
- aeron-driver/src/main/c/aeron_min_flow_control.c
- aeron-driver/src/main/c/aeronmd.h
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/test/c/aeron_driver_configuration_test.cpp
- aeron-driver/src/test/c/aeron_flow_control_test.cpp
Adds lots of configuration environment var/property/programmatic configuration on the c driver for:
- Tagged flow control strategy supplier (including by name).
- Min/Tagged flow control timeouts.
- Default group rtag.
- Default group required size.
Removes thread_once configuration for min/tagged timeouts.
Renaming for consistency.
With the exception of handling the require group size, this bring parity with the Java driver.
> C driver flow control configuration

- aeron-driver/src/main/c/aeron_flow_control.c
- aeron-driver/src/main/c/aeron_flow_control.h
- aeron-driver/src/main/c/aeron_min_flow_control.c
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/test/c/aeron_flow_control_test.cpp
Follows the Java implementation, unit test provided.
I have a system test for the Java side, but it is dependent on #849 being merged first.
> Use required group size in tagged flow control to affect publication connected status

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java
- aeron-client/src/main/java/io/aeron/AeronCloseHelper.java
- build.gradle
Free allocated direct `ByteBuffers` when a `Context#close` is called and the context was configured with the `shouldFreeBuffersOnClose(true)`.
There is at least one open question, i.e. are we allowed to free `ByteBuffers` for the `DataTransportPoller` and `ControlTransportPoller`?
> [Java] Add an option to free allocated direct ByteBuffers

- aeron-driver/src/main/c/aeron_driver.c
The media driver always produced the same sequence of session IDs.
- `rand()` was apparently not seeded properly (yet it should have been, I need to check why)
- `rand() * INT_MAX` would always cause an overflow
- This uses `rand_s` instead of `rand` for better randomness and to avoid the dependency on a seed (it better aligns to what is done on other platforms)
> [C] Fix aeron_randomised_int32 on Windows

- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/main/java/io/aeron/archive/RecordingReader.java
- aeron-client/src/main/java/io/aeron/Aeron.java
- aeron-client/src/main/java/io/aeron/LogBuffers.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/io/aeron/driver/buffer/MappedRawLog.java
- aeron-samples/src/main/java/io/aeron/samples/CncFileReader.java
For the symmetry with other places where we free buffers we should null-out the corresponding field reference before freeing/un-mapping the underlying buffer.
> [Java] Set field pointing to MappedByteBuffer to null before calling IoUtil#unmap

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_flow_control.c
- aeron-driver/src/main/c/aeron_flow_control.h
- aeron-driver/src/main/c/aeron_min_flow_control.c
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/c/aeronmd.h
- aeron-driver/src/main/java/io/aeron/driver/Configuration.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/io/aeron/driver/MinMulticastFlowControl.java
- aeron-driver/src/main/java/io/aeron/driver/TaggedMulticastFlowControl.java
- aeron-driver/src/test/c/aeron_flow_control_test.cpp
- aeron-driver/src/test/java/io/aeron/driver/TaggedMulticastFlowControlTest.java
- aeron-system-tests/src/test/java/io/aeron/TaggedFlowControlTest.java
- aeron-system-tests/src/test/java/io/aeron/test/CTestMediaDriver.java
- Use groupMinSize and the name to require a group of a particular size to indicate connectivity in tagged multicast flow control.
- Fix bug in C driver around use of flow control to handle connectivity.
- Use senderLimit as the position returned from tagged flow control (onStatusMessage, onIdle) when the group size had not been met.
- Tests.
> Tagged Flow Controls, renaming and fixing

- aeron-driver/src/main/c/aeron_agent.c
- aeron-driver/src/main/c/aeron_congestion_control.c
- aeron-driver/src/main/c/aeron_congestion_control.h
- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_flow_control.c
- aeron-driver/src/main/c/aeron_socket.c
- aeron-driver/src/main/c/aeron_socket.h
- aeron-driver/src/main/c/aeron_termination_validator.c
- aeron-driver/src/main/c/aeron_windows.h
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/concurrent/aeron_atomic64_gcc_x86_64.h
- aeron-driver/src/main/c/concurrent/aeron_atomic64_msvc.h
- aeron-driver/src/main/c/concurrent/aeron_thread.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-driver/src/main/c/media/aeron_udp_transport_poller.c
- aeron-driver/src/main/c/media/aeron_udp_transport_poller.h
- aeron-driver/src/main/c/protocol/aeron_udp_protocol.c
- aeron-driver/src/main/c/util/aeron_arrayutil.h
- aeron-driver/src/main/c/util/aeron_clock.c
- aeron-driver/src/main/c/util/aeron_dlopen.c
- aeron-driver/src/main/c/util/aeron_dlopen.h
- aeron-driver/src/main/c/util/aeron_error.c
- aeron-driver/src/main/c/util/aeron_fileutil.c
- aeron-driver/src/main/c/util/aeron_parse_util.c
- aeron-driver/src/main/c/util/aeron_strutil.c
Here's another round of Windows fixes for the media driver. See individual commit messages for details. The cleanup commit mostly gets rid of some warnings and makes the IDE happier.
There are still other things I'll need to fix though, I'll send the fixes later.
> [C] Windows fixes

- aeron-system-tests/src/test/java/io/aeron/archive/ReplayMergeTest.java
- aeron-test-support/src/main/java/io/aeron/test/Tests.java
Changed the ReplayMergeTest to take a different approach with regards to timeouts.  It would be useful to merge in a see whether this provides better feedback on the failures seen from that test.
- Renames test methods for clarity.
- Outputs messages send as well as received.
- Runs loops as lamdbas with separate timeouts using assertions to determine exit conditions.
> Replay merge test update

- CMakeLists.txt
- aeron-driver/src/main/c/aeron_driver.c
- `mkdir` has a different signature on Windows
- Suppress warning about POSIX function names
Part of #863
> [C] Fix warnings on Windows

- aeron-driver/src/main/c/util/aeron_fileutil.c
- Don't try to silently adjust the supplied length to the file size
- `off_t` is 32 bits, so `offset >> 32` generates a warning
Part of #863
> [C] Fix aeron_mmap on Windows

- aeron-driver/src/main/c/aeron_agent.c
- aeron-driver/src/main/c/concurrent/aeron_thread.c
- aeron-driver/src/main/c/concurrent/aeron_thread.h
- A function with the wrong signature was being passed to `CreateThread`
- The thread handle was never closed
- Failure to start a thread was not detected
Part of #863
> [C] Fix thread handling on Windows

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_socket.c
- aeron-driver/src/main/c/aeron_socket.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.h
- aeron-driver/src/main/c/util/aeron_http_util.c
- The `SOCKET` type was incorrectly cast to `int`, even though it's larger
- Renamed `aeron_fd_t` to `aeron_socket_t` as a socket handle is not a file descriptor on Windows
Part of #863
> [C] Fix sockets on Windows

- aeron-driver/src/main/c/concurrent/aeron_distinct_error_log.c
- aeron-driver/src/main/c/concurrent/aeron_distinct_error_log.h
- aeron-driver/src/main/c/concurrent/aeron_thread.c
- aeron-driver/src/main/c/concurrent/aeron_thread.h
- Lock/unlock did not work as an indirection was missing
- Made the function prototypes match the Linux version
- Added `aeron_mutex_destroy`
Part of #863
> [C] Fix mutexes on Windows

- aeron-system-tests/src/test/java/io/aeron/archive/ReplayMergeTest.java
- aeron-test-support/src/main/java/io/aeron/test/Tests.java
This takes a different approach to getting information regarding timeouts in tests.  The call would explicitly yield, but pass in context information about where the code is up to.
> Add context information when waiting in spin loops

- aeron-driver/src/main/c/aeron_agent.c
- aeron-driver/src/main/c/aeron_alloc.c
- aeron-driver/src/main/c/aeron_data_packet_dispatcher.c
- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_receiver.c
- aeron-driver/src/main/c/aeron_driver_sender.c
- aeron-driver/src/main/c/aeron_retransmit_handler.c
- aeron-driver/src/main/c/aeron_system_counters.c
- aeron-driver/src/main/c/collections/aeron_int64_to_ptr_hash_map.h
- aeron-driver/src/main/c/collections/aeron_str_to_ptr_hash_map.h
- aeron-driver/src/main/c/concurrent/aeron_distinct_error_log.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
- aeron-driver/src/main/c/media/aeron_udp_transport_poller.c
- aeron-driver/src/main/c/util/aeron_error.c
- aeron-driver/src/main/c/util/aeron_error.h
- aeron-driver/src/main/c/util/aeron_fileutil.c
- aeron-driver/src/main/c/util/aeron_http_util.c
- aeron-driver/src/main/c/util/aeron_properties_util.c
The issue I'm trying to solve:
- WinAPI functions return error codes through `GetLastError()`, not through `errno`
- `strerror` is [not very useful](https://docs.microsoft.com/en-us/cpp/c-language/strerror-function?view=vs-2019) on Windows, so mapping error codes wouldn't work
I came up with this refactor which I hope you'll find acceptable. It ends up simplifying the `aeron_set_err` calls.
I've added an `aeron_set_err_from_last_err_code` function which will act the same way as `aeron_set_err`, except it will automatically append an error message based on the last error code. This will use `GetLastError` and `FormatMessage` on Windows, and `strerror(errno)` on other platforms.
- This will still work on Windows with the C library file I/O calls, since they call WinAPI
- WinSock returns …
> [C] Refactor error handling to improve error messages on Windows

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_sender.c
- aeron-driver/src/main/c/aeron_flow_control.c
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/c/aeron_position.c
- aeron-driver/src/main/c/aeron_socket.c
- aeron-driver/src/main/c/aeron_socket.h
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/concurrent/aeron_atomic64_msvc.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
This fixes all remaining level 3 MSVC warnings in the media driver.
- Added `aeron_getsockopt`/`aeron_setsockopt` as the Windows version declares `optval` as `char*` instead of `void*`, which causes warnings.
- Added various casts:
- Term offsets and lengths need to fit in an `int32_t`, they are declared as `size_t` in `aeron_uri_publication_params_stct` but their value is then checked to fit inside the valid range.
- Unfortunately, `iovec.iov_len` is `uint32_t` on Windows. I inserted casts because of that but I could compile them conditionally if you prefer.
> [C] Fix remaining MSVC warnings in the media driver

- aeron-agent/src/main/java/io/aeron/agent/ClusterEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterInterceptor.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventEncoderTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventLoggerTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogPublisher.java
- aeron-cluster/src/main/java/io/aeron/cluster/MemberStatusAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/MemberStatusPublisher.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java
This causes a bug where a node that that dies and leaves that cluster and is then restarted and rejoins the cluster may end up having differing state from the leader as it's own isStartup flag gets used to determine if any sessions should be closed.  This records the isStartup flag from the leader in the leadership term event and uses that value to determine is session should be closed.
This can cause some strange behaviour around sessions and visibility of events from the cluster.  It was causing `ClusterTest::shouldRecoverWhenLastSnapshotIsInvalidAndWasBetweenTwoElections` to be intermittent.
> [Java] Change the use of the isStartup flag for closing existing sessions.

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/test/c/aeron_driver_conductor_network_test.cpp
- aeron-driver/src/test/c/aeron_driver_conductor_test.h
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
- aeron-system-tests/src/test/java/io/aeron/test/CTestMediaDriver.java
- Enables system tests
- Removes restriction of having the control address specified when using `control-mode=manual`
- Fixes logic bug when removing destinations.
> Fixes for MDC in the C media driver

- aeron-driver/src/main/java/io/aeron/driver/DriverNameResolver.java
- aeron-system-tests/src/test/java/io/aeron/DriverNameResolverTest.java
- aeron-system-tests/src/test/java/io/aeron/test/CTestMediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/test/DriverOutputConsumer.java
- aeron-system-tests/src/test/java/io/aeron/test/MediaDriverTestWatcher.java
Update DriverNameResolverTest to better support C implementation.  Add additional error reporting information for failed C driver tests (environment variables and exit codes).  Update shouldSeeNeighborsViaGossip so that without the fix would fail consistently.
> [Java] Fix intermittency in DriverNameResolver.

- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/main/c/aeron_flow_control.c
- aeron-driver/src/main/c/aeron_system_counters.c
- aeron-driver/src/main/c/aeron_system_counters.h
- aeron-driver/src/main/c/util/aeron_env.c
- aeron-driver/src/main/c/util/aeron_env.h
- aeron-driver/src/test/c/aeron_name_resolver_test.cpp
- Remove warnings
- Error counters
- Use static assert to prevent heap corruption in the future.
> Various small fixes.

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolTests.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogViewTest.java
- aeron-archive/src/test/java/io/aeron/archive/ListRecordingsForUriSessionTest.java
- aeron-archive/src/test/java/io/aeron/archive/ListRecordingsSessionTest.java
When the last fragment in the segment file straddle page boundaries Aeron will attempt to verify if it was persisted correctly by looking at the following:
- if `Checksum` was configured either on the Archive via `io.aeron.archive.Archive.Context#recordChecksum()` or specified as a parameter to the `ArchiveTool` then it will be used to verify the checksum of the last fragment. Upon match fragment will be considered complete.
- if `Checksum` was not configured or if the check failed then Aeron will look for non-zero bytes in every page since the straddle offset. If all pages have at least one non-zero byte then the fragment is considered complete. 
_Note: In case if zeroes are the valid data only the `Checksum` can be used to recover such fragments._
> [Java] Page straddle recovery

- .github/workflows/ci.yml
- aeron-client/src/main/cpp/ClientConductor.cpp
- aeron-client/src/main/cpp/command/ErrorResponseFlyweight.h
- aeron-client/src/main/cpp/util/Exceptions.h
- aeron-client/src/test/cpp/ClientConductorTest.cpp
To support the changes in the C driver for handling rapid remove/add subscriptions.
> [C++] Use WARN error category when encountering temporary failures.

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolTests.java
- The tool exits with a negative exit code in case any errors have been found. This helps to run the tool automatically.
- ActionConfirmation has been made public so that it is possible to run public 'verify' methods from the code in another packages
- Public verify/verifyRecording methods now return boolean result indicating presence or absence of errors
> [Java] 'Verify' archive tool improvements

- aeron-driver/src/test/c/aeron_receiver_test.h
std:array<> not zero-initialized without calling the constructor directly.
Refer to https://stackoverflow.com/questions/18295302/default-initialization-of-stdarray
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
> [CPP] fix std::array not initialized bug

- aeron-driver/src/main/c/aeron_driver.c
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
> [C] '+' and ':' are not valid win32 path symbol. replace them with '-'

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
- aeron-driver/src/main/java/io/aeron/driver/Configuration.java
Reapplies #939 after test failure and adds an additional parameter to control cool off period.
30 seconds ensures any lingers resources will be closed.
> Add backoff period after exception in ClusterBackupAgent - 2nd attempt

- aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestNode.java
- aeron-test-support/src/main/java/io/aeron/test/DataCollector.java
- aeron-test-support/src/test/java/io/aeron/test/DataCollectorTest.java
- build.gradle
When any test in `ClusterTest` fails all of its data will be preserved and copied into `build/test-output/$test_name[_uniqueId]` directory, where `$test_name` is the name derived from test class plus method name and `_uniqueId` is a unique suffix added if such directory already exists (e.g. from previous tests runs or if it's a parameterized test).
The `build/test-output` folders are added to the `crash_logs` when `copyCrashLogs` Gradle task is executed and hence will be preserved in CI.
Here is an example of data preserved for `ClusterTest` when a test fails:
```
aeron-cluster
└── build
└── test-output
└── io.aeron.cluster.ClusterTest-shouldNotifyClientOfNewLeader
├── aeron-username-0
│   ├── archive
│   │   ├── 0-0.rec
│   │   ├── archive-mark.dat
│   │   └── archive.catalog
│   ├── …
```
> [Java] Preserve Archive/MediaDriver/Service/ConsensusModule data upon cluster test failure

- aeron-client/src/main/cpp/FragmentAssembler.h
Old g++ has this error on Centos7:
/usr/include/c++/4.8.2/bits/stl_pair.h:112:26: note:   no known conversion for argument 2 from ‘unsigned int’ to ‘const aeron::BufferBuilder&’
/usr/include/c++/4.8.2/bits/stl_pair.h:108:26: note: constexpr std::pair<_T1, _T2>::pair() [with _T1 = const int; _T2 = aeron::BufferBuilder]
_GLIBCXX_CONSTEXPR pair()
> Port for g++ 4.8.5 on centos7 compile

- aeron-driver/src/main/c/aeron_driver_common.h
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_ipc_publication.c
- aeron-driver/src/main/c/aeron_ipc_publication.h
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/c/aeron_network_publication.h
- aeron-driver/src/main/c/aeron_publication_image.c
- aeron-driver/src/main/c/aeron_publication_image.h
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.h
- aeron-driver/src/test/c/CMakeLists.txt
- aeron-driver/src/test/c/aeron_driver_agent_test.cpp
- aeron-driver/src/test/c/agent/aeron_driver_agent_test.cpp
- cppbuild/cppbuild
- Logging of the untethered subscription state change
- Add missing options to the `cppbuild`'s help output
- Fix logging constants to be power of two
For the logging changes I'm not sure if `aeron_driver_context.c` is the right place for the implementation of the `aeron_untethered_subscription_state_change` function or if it would be better to define it as `inline` in the `aeron_driver_common.h`.
> [C] Add logging for the untethered subscription state change

- aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
Fix warnings when building on release mode.
`AtomicBuffer.h:451:43: error: unused parameter ‘index’ [-Werror=unused-parameter]`
> [C++]: Fix unused-parameter warning on Release.

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-system-tests/src/test/java/io/aeron/SessionSpecificPublicationTest.java
Add system test to show external behaviour as well.
> [C] Don't allow session ids on network publications to be re-used until the publication is completely closed.

- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/main/c/aeron_driver_receiver.c
- aeron-driver/src/main/c/aeron_driver_sender.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.h
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.h
- aeron-driver/src/test/c/media/aeron_udp_channel_transport_loss_test.cpp
To pass back and forth to see if comprehensive enough.
@mikeb01 see if this seems logical.
Interceptor changes to include transport in the incoming path and various notifications of transport/publication/image events, and addition of per interceptor state to transport.
> interceptor changes

- aeron-client/src/main/c/util/aeron_dlopen.c
- aeron-client/src/main/c/util/aeron_dlopen.h
Windows.h is a very big header that pulls a lot of things.
> [C] Move Windows.h out of aeron_dlopen.h

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
> [C] use aeron_epoch_clock instead of aeron_agent_epoch_clock

- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/ArchiveInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventEncoderTest.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventLoggerTest.java
- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
Catalog will auto-resize from within `io.aeron.archive.Catalog#addNewRecording(long, long, long, long, int, int, int, int, int, int, java.lang.String, java.lang.String, java.lang.String)` method whenever Catalog is full. If resize is not possible then an `ArchiveException` will be thrown.
The resize event is logged in the Agent under new event type `CATALOG_RESIZE`. The logging will print old maxEntries/catalogLength and the new ones after the resize, e.g.:
```
24 entries (100 bytes) => 777 entries (10000000000 bytes)
```
> [Java] Auto-resize Catalog when full.

- aeron-client/src/main/c/aeron_client_conductor.c
- aeron-client/src/main/c/aeron_client_conductor.h
- aeron-client/src/main/c/aeron_counter.c
- aeron-client/src/main/c/aeron_counter.h
- aeron-client/src/main/c/aeron_exclusive_publication.c
- aeron-client/src/main/c/aeron_exclusive_publication.h
- aeron-client/src/main/c/aeron_publication.c
- aeron-client/src/main/c/aeron_publication.h
- aeron-client/src/main/c/aeron_subscription.c
- aeron-client/src/main/c/aeron_subscription.h
- aeron-client/src/main/c/aeronc.h
- aeron-client/src/test/c/aeron_client_conductor_test.cpp
- aeron-driver/src/test/c/aeron_c_system_test.cpp
- aeron-samples/src/main/c/basic_publisher.c
- aeron-samples/src/main/c/basic_subscriber.c
- aeron-samples/src/main/c/cping.c
- aeron-samples/src/main/c/cpong.c
- aeron-samples/src/main/c/rate_subscriber.c
- aeron-samples/src/main/c/streaming_exclusive_publisher.c
- aeron-samples/src/main/c/streaming_publisher.c
This is useful for knowing when client resourcing can be cleaned up.  The common example is clientd values assigned to subscription's image available/unavailable notifications.  Notifications for publications, exclusive publications, and counters are there for completeness.
> [C] Add notifications that resources (publications, subscriptions, counters) have been closed.

- aeron-archive/src/main/java/io/aeron/archive/client/AeronArchive.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java
- aeron-client/src/main/java/io/aeron/ChannelUri.java
- aeron-client/src/main/java/io/aeron/Subscription.java
- aeron-client/src/test/java/io/aeron/ChannelUriTest.java
- aeron-client/src/test/java/io/aeron/SubscriptionTest.java
This PR implements a feature that allows `aeron.archive.control.response.channel` to be configured without specifying an explicit port number.
Below are the examples of valid configurations:
- `aeron:udp?endpoint=localhost:8020` - listen on port {@code 8020} on localhost.
- `aeron:udp?endpoint=192.168.10.10:8020` - listen on port {@code 8020} on `192.168.10.10`.
- `aeron:udp?endpoint=localhost:0` - in this case the port is unspecified and the OS will assign a free port from an  [ephemeral port range](https://en.wikipedia.org/wiki/Ephemeral_port).
> [Java] Allow control response channel in the Archive to be configured without specifying the port.

- aeron-client/src/main/c/aeron_image.c
- aeron-client/src/main/c/aeron_image.h
- aeron-client/src/main/c/aeron_subscription.c
- aeron-client/src/main/c/aeronc.h
- aeron-client/src/test/c/aeron_fragment_assembler_test.cpp
- aeron-client/src/test/c/aeron_image_test.cpp
- aeron-samples/src/main/c/basic_subscriber.c
Needed in order to access the initial_term_id in the C++ Wrapper.  Useful for feature parity with the Java driver also.
> [C] Add initial term id to message header in C API.

- aeron-client/src/main/java/io/aeron/Subscription.java
- aeron-client/src/test/java/io/aeron/SubscriptionTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/TestCluster.java
- aeron-system-tests/src/test/java/io/aeron/ResolvedEndpointSystemTest.java
It is now possible to specify zero port in `egressChannel` configuration in which case a port from an ephemeral range will be used.
> [Java] Add support for zero port in `egressChannel` for AeronCluster.

- aeron-client/src/main/c/aeron_client.c
- aeron-client/src/main/c/aeron_exclusive_publication.c
- aeron-client/src/main/c/aeron_publication.c
- aeron-client/src/main/c/aeron_subscription.c
- aeron-client/src/main/c/aeronc.h
- aeron-client/src/test/c/aeron_client_conductor_test.cpp
* Add/correct functions declared in aeronc.h
* Uses a single poll function per resource for checking for the completion of destination commands (add/remove).  This matches the shape of the C++ API which has a single findDestinationResponse function shared for both adds and removes.
* Removes the older add/remove destination functions that did not use a async tracking for completion.
> [C] Collapse destination add/remove poll to a single function per resource to match the shape of the C++ API.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
If Appended Position counter is re-used then the ConsensusModule would update the commit position counter to an incorrect value. Also includes a fix for an incorrect counter re-use timeout.
> Avoid issue where commit-pos counter is updated when cluster is CLOSED

- .gitignore
- aeron-samples/scripts/cluster/script-common
- aeron-samples/src/docs/asciidoc/Cluster-Tutorial.asciidoc
- aeron-samples/src/main/java/io/aeron/samples/cluster/tutorial/BasicAuctionClusterClient.java
- aeron-samples/src/main/java/io/aeron/samples/cluster/tutorial/BasicAuctionClusteredServiceNode.java
- buildSrc/src/main/java/io/aeron/build/AsciidoctorPreprocessTask.java
- Fix Gradle deprecation warnings.
- Use port 0 for egress and control response channels.
- Assign Aeron dir name to Archive.Context.
- Ignore cluster tutorial output files/dirs in Git.
> [Java] More cluster tutorial fixes.

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.h
- aeron-driver/src/test/c/agent/aeron_driver_agent_test.cpp
- Restore dynamic event logging.
- Add checks if dynamic event logging is enabled.
- Use array of structs to keep track of event descriptors.
> [C] Restore dynamic logging events.

- aeron-client/src/main/c/concurrent/aeron_spsc_rb.c
Changes:
- Use plain write for `head_cache_position`.
- Pre-zero also `msg_type_id` as in Java implementation.
- Use `AERON_PUT_ORDERED` to write length field in `aeron_spsc_rb_try_claim` to ensure that the pre-zeroing of the next header is done first, i.e. to avoid re-ordering.
> [C] Fixes to spsc_rb.

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolTests.java
This PR adds `delete-orphaned-segments` command to the `ArchiveTool` which detects and deletes orphaned segments as per #1098. In addition it will also delete segment files with malformed names (e.g. without position info or with non-parsable or negative position etc.).
Fixes #1098.
> [Java] ArchiveTool: delete orphaned segments

- aeron-samples/src/main/java/io/aeron/samples/AeronStat.java
Addresses minor typos in the help displayed with `-h`:
- `streamId` should be `stream`
- `sessionId` should be `session`
> [Java] Fix AeronStat arguments in help

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogPublisher.java
- aeron-samples/scripts/cluster/agent-ns
- aeron-samples/scripts/cluster/basic-auction-client-ns
- aeron-samples/scripts/cluster/basic-auction-cluster
- aeron-samples/scripts/cluster/basic-auction-cluster-ns
- aeron-samples/scripts/cluster/remove-namespaces
- aeron-samples/scripts/cluster/setup-namespaces
- aeron-samples/src/main/java/io/aeron/samples/cluster/EchoService.java
- aeron-samples/src/main/java/io/aeron/samples/cluster/EchoServiceNode.java
- aeron-samples/src/main/java/io/aeron/samples/cluster/tutorial/BasicAuctionClusterClient.java
- aeron-samples/src/main/java/io/aeron/samples/cluster/tutorial/BasicAuctionClusteredServiceNode.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterNetworkTopologyTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/TopologyTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/launcher/FileResolveUtil.java
- aeron-test-support/src/main/java/io/aeron/test/launcher/RemoteLaunchClient.java
- aeron-test-support/src/main/java/io/aeron/test/launcher/RemoteLaunchServer.java
- aeron-test-support/src/test/java/io/aeron/test/launcher/RemoteLauncherTest.java
- build.gradle
There is still one outstanding test failure as result of this change.  In `shouldRecoverQuicklyAfterKillingFollowersThenRestartingOne` it appears that when extending the recording the image does not become available to the archive's subscription therefore it never constructs the recording counter and ConsensusModule's conductor times out.
> Topology tests & allow multicast for log channel

- aeron-agent/src/main/java/io/aeron/agent/EventConfiguration.java
- aeron-agent/src/test/java/io/aeron/agent/EventConfigurationTest.java
Adds:
- `aeron.event.log.disabled`
- `aeron.event.archive.log.disabled`
- `aeron.event.cluster.log.disabled`
That allows disabling of specific events from the logging, e.g. `-Daeron.event.log=all` `-Daeron.event.log.disabled=FRAME_IN,FRAME_OUT` is everything except frames.
> Event log disable

- aeron-client/src/main/c/util/aeron_fileutil.c
- aeron-client/src/main/cpp/LogBuffers.cpp
- aeron-client/src/main/cpp/util/MemoryMappedFile.cpp
- aeron-client/src/main/cpp/util/MemoryMappedFile.h
- aeron-client/src/test/cpp/ClientConductorTest.cpp
- aeron-client/src/test/cpp/util/MemoryMappedFileTest.cpp
Prefaulting can be slow. MMAP_POPULATE speeds that up a bit as the
prefaulting happens directly in the kernel on creation and doesn't
require on demand interrupts and context switches.
I have left the windows version as is.
> [C++] Use MMAP_POPULATE for faster prefaulting on Linux

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
ClusterBackupAgent polls for cluster archive client errors, but doesn't do anything with the returned value, so they become silently ignored. We should check instead, like for the backup archive.
> [Java] Actually check for cluster archive client errors in ClusterBackupAgent

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-system-tests/src/test/java/io/aeron/SpySubscriptionTest.java
Currently when a publication is created, endpoint from an old one can be reused. However, the tag is not checked and as a result publication and endpoint have different tags. Spy subscriptions then may hang waiting for image.
I have added a test - if removed publication has not been cleaned up by timeout, then the endpoint is reused and the test does not pass.
> check tag when reusing send channel endpoint 

- README.md
I tried following the top level README.md to build Aeron and run the samples today and found the sample commands didn't work. I think using the aeron-all jar is consistent with the samples scripts. 
I also thought it was worth adding a reference to the aeron-samples directory to send people in the right direction.
> [Doc] Fix sample commands in top level README.md.

- aeron-archive/src/main/java/io/aeron/archive/RecordingEventsProxy.java
Add the length of the message header to what must be written.
> Fix a short write in sending the RecordingStarted event.

- aeron-agent/src/main/java/io/aeron/agent/ClusterEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/CollectingEventLogReaderAgent.java
- aeron-agent/src/main/java/io/aeron/agent/CollectingEventLogReaderAgentMBean.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogReaderAgent.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/DataCollector.java
- aeron-test-support/src/main/java/io/aeron/test/Tests.java
- build.gradle
- Captures the configure Aeron event logs in memory, when requested and dumps them into an `events.log` in the failure output if the test fails.
- Currently only configured to work on the `slowTest` task and with ClusterTest specifically.
> Event log dump on test failure

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java
- aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java
- aeron-cluster/src/test/java/io/aeron/cluster/RecordingLogTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterToolTest.java
This PR changes `RecordingLog` to allow term and snapshot entries to be added out of order.
- A TERM can be added out of order with other terms.
- A snapshot can be added out of order with other entries.
- A TERM must be added before a snapshot for the same `leadershipTermId` (validation).
- `NULL_VALUE` is not allowed as `recordingId` (validation).
- All TERM entries must added with the same `recordingId` (validation).
- ClusterTool now has command `sort-recording-log` which re-arranges entries on disc to match the in-memory order.
> [Java] Out of order RecordingLog

- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/DriverInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventEncoderTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverLoggingAgentTest.java
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_min_flow_control.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.h
- aeron-driver/src/main/java/io/aeron/driver/AbstractMinMulticastFlowControl.java
- aeron-driver/src/test/c/agent/aeron_driver_agent_test.cpp
This PR adds agent logging for min/group flow control strategies when a receiver is added or removed.
It also has other changes:
- [C] Fix receivers array length assignment upon remove.
- [Java] Fix logging configuration of name resolution when both add and remove are logged.
- [C/Java] Remove commas as field separators.
> Flow control logging

- .gitignore
- aeron-agent/src/main/java/io/aeron/agent/ArchiveEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/ClusterEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/ConfigOption.java
- aeron-agent/src/main/java/io/aeron/agent/DynamicLoggingAgent.java
- aeron-agent/src/main/java/io/aeron/agent/EventConfiguration.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogReaderAgent.java
- aeron-agent/src/test/java/io/aeron/agent/AgentTests.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveEventCodeTest.java
- aeron-agent/src/test/java/io/aeron/agent/ArchiveLoggingAgentTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterEventCodeTest.java
- aeron-agent/src/test/java/io/aeron/agent/ClusterLoggingAgentTest.java
- aeron-agent/src/test/java/io/aeron/agent/ConfigOptionTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverLoggingAgentTest.java
- aeron-agent/src/test/java/io/aeron/agent/EventConfigurationTest.java
- aeron-samples/scripts/dynamic-logging
- aeron-samples/scripts/dynamic-logging.cmd
- build.gradle
This PR adds scripts that allow enabling and disabling Agent-based logging of Aeron components.
The general form of the command is:
```bash
dynamic-logging <pid> <command> [config files...]
```
where `<pid>` is the JVM process ID and `<command>` is either `start` or `stop`. One can also pass an optional list of config property files or use `JVM_OPTS` env var instead.
Here is an example of enabling logging for the admin events of media driver process `1111` on Linux:
```bash
JVM_OPTS="-Daeron.event.log=admin" ./dynamic-logging 1111 start
```
And on Windows:
```batch
set "JVM_OPTS=-Daeron.event.log=admin" && dynamic-logging 1111 start
```
By default the log will be written to the `stdout` of the target process. Logging to a file can be specified via the `aeron.event.log.filename` property.
> [Java] Dynamic logging

- aeron-driver/src/test/java/io/aeron/driver/OptimalMulticastDelayGeneratorTest.java
Problem:
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution, and this behavior is kept for a repetition structure.
Solution:
The RepeatedTest annotation make it possible to repeat a test multiple times, reporting the result of each execution individually. This way, we were able to make 1 original test containing a repetition structure into many individual and independently executed tests.
> Refactored test using RepeatedTest annotation

- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/test/c/aeron_c_system_test.cpp
- Allow for bindings to be updated before calling `aeron_driver_init`.
- Add internal functions for find used and free slots in the bindings_clientd list.
> C driver preallocate bindings

- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
Observed this exception during failover testing:
```
java.lang.NullPointerException
at io.aeron.cluster.client.AeronCluster$AsyncConnect.awaitPublicationConnected(AeronCluster.java:1600)
at io.aeron.cluster.client.AeronCluster$AsyncConnect.poll(AeronCluster.java:1529)
....
```
I believe thing can occur in the following scenario:
Step 1 => Step 2 => Step 3 => Redirect (member X) => Step 1 => Step 2 => Step 3 => Redirect (member Y) => Step 1 (Exception!)
This will occur due to the publication for member Y being closed at the point the client is redirected to member X.
> Fix NPE in cluster client after multiple redirects.

- aeron-all/README.md
Attempt to build `aeron-all` from fresh git clone, using `./gradlew :aeron-all:build` produces the following error:
```
Could not set process working directory to '$CLONE_DIR/aeron-all': could not setcwd() (errno 2: No such file or directory)
```
The `aeron-all` directory is missing. I've added simple `README.md` file (instead of `.gitkeep` as [suggested here](https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep#comment15172056_7229996)) to create the directory upon fresh clone.
> Missing aeron-all directory after fresh checkout

- aeron-agent/src/main/java/io/aeron/agent/CommonEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/CommonEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/DriverInterceptor.java
- aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
- aeron-agent/src/test/java/io/aeron/agent/CommonEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventDissectorTest.java
- Refactor out common code for handling addresses and socket addresses.  
- Test for dissecting IPv6 addresses.
- Use URL style formatting for IPv6 addresses (i.e. surround with `[]`).
> Add logging for name resolutions.  

- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-client/src/main/java/io/aeron/ChannelUri.java
- aeron-client/src/main/java/io/aeron/ChannelUriStringBuilder.java
- aeron-client/src/test/java/io/aeron/ChannelUriStringBuilderTest.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationSubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/ResolvedEndpointSystemTest.java
- aeron-system-tests/src/test/java/io/aeron/SpySubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/archive/ReplicateRecordingTest.java
Support constructing a ChannelUriStringBuilder from an existing URI (String or ChannelUri).  Use Aeron::nextCorrelationId throughout tests to show most appropriate usage.  Encapsulate handling of tagged session ids in the ChannelUriStringBuilder.
> Use Aeron::nextCorrelationId in tests for tags.  Update ChannelUriStringBuilder to build from existing URIs.

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterMember.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusPublisher.java
- aeron-system-tests/src/test/java/io/aeron/cluster/AppointedLeaderTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterBackupTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterToolTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/DynamicMembershipTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/MultiClusteredServicesTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/MultiModuleSharedDriverTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/MultiNodeTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ServiceIpcIngressTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/SingleNodeTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/ClusterTests.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
And re-resolve upon a CANVASS message from the member missing its publication.
Lots of tweaks to the cluster tests to allow name resolution failures and recovery.  Tests for starting a cluster with a missing member and one where the majority of nodes become available during an election.
> Allow name resolution failure on construction of consensus publications

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
I have found that when using a dedicated media driver for Aeron Archive, I have needed to supply a nanoClock in order to debug, as by default the SystemNanoClock.INSTANCE is used and I could not see a way to override that.
> Add nanoTime to AeronArchive.Context

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java
To ensure that an `Election` can recover from exceptions which are triggered outside of the `Election.doWork` cycle.
> [Java] Reset Election state upon exception.

- aeron-client/src/main/c/uri/aeron_uri.h
- aeron-client/src/test/c/aeron_client_conductor_test.cpp
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_conductor.h
- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.h
- aeron-driver/src/main/c/media/aeron_receive_destination.c
- aeron-driver/src/main/c/media/aeron_receive_destination.h
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.h
- aeron-driver/src/main/c/media/aeron_udp_channel.c
- aeron-driver/src/main/c/media/aeron_udp_channel.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-driver/src/main/c/uri/aeron_driver_uri.c
- aeron-driver/src/main/c/uri/aeron_driver_uri.h
- aeron-driver/src/test/c/CMakeLists.txt
- aeron-driver/src/test/c/aeron_c_cnc_test.cpp
- aeron-driver/src/test/c/aeron_c_local_addresses_test.cpp
- aeron-driver/src/test/c/aeron_c_system_test.cpp
- aeron-driver/src/test/c/aeron_driver_uri_test.cpp
- aeron-driver/src/test/c/aeron_errors_test.cpp
- aeron-driver/src/test/c/aeron_packet_timestamps_test.cpp
- aeron-driver/src/test/c/aeron_publication_image_test.cpp
- aeron-driver/src/test/c/aeron_receiver_test.h
- aeron-driver/src/test/c/aeron_test_base.h
- aeron-driver/src/test/c/aeron_test_udp_bindings.h
Add the ability to get RX packet timestamps added to incoming messages.  This is enabled using the URI parameter `pkt-ts-offset`.  If this is 0 or greater, the 64 bit timestamp will be written into that position within the body of the message.  The special value `reserved` can also be used, in that case it will be written into reserved value field with the data header.  The timestamp is a 64bit count of nanoseconds since epoch.
If an incoming packet contains multiple fragments, it will only write the timestamp to the first fragment in the batch (to avoid having to scan a batch for each header).
The implementation currently only works with the C driver in Linux.
The configuration is set on the receive channel endpoint.  The `pkt-ts-offset` is used in subscription matching so creating two …
> C driver packet timestamps

- aeron-archive/src/main/cpp/client/AeronArchive.cpp
findSubscription() may return a null pointer that is used unchecked in step 1.
> [C++] Archive Client AsyncConnect::poll: Avoid proceeding to step 1 until m_subscription is non-null

- aeron-agent/src/test/java/io/aeron/agent/DriverEventDissectorTest.java
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/java/io/aeron/driver/media/UdpChannel.java
- aeron-driver/src/test/c/agent/aeron_driver_agent_test.cpp
Various fixes and alignment of logging messages between C and Java.
> [C/Java] Logging agent fixes.

- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/test/c/aeron_name_resolver_test.cpp
With this PR the bootstrap neighbour lookup is always performed via `bootstrap_resolver` which also makes testing much simpler.
> [C] Make bootstrap resolver configurable for driver name resolver.

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.h
- aeron-driver/src/test/c/aeron_timestamps_test.cpp
- aeron-driver/src/test/c/media/aeron_udp_channel_transport_loss_test.cpp
Configure timestamp tests to use loss interceptor with 0 loss to exercise/test that code path.
> [C/C++] Pass media timestamp through the C driver interceptor chain.

- CMakeLists.txt
- aeron-client/src/main/c/aeron_socket.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_loss.c
- aeron-driver/src/test/c/aeron_udp_channel_test.cpp
- cppbuild/cppbuild.cmd
**Note:** I haven't added sanitise Windows build to CI, because it currently reports lots of _false positives_ in the form of `attempting free on address which was not malloc()-ed`.
For example:
```powershell
==8312==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x11d73a0a2200 in thread T0
#0 0x7ff7b3c3fc5c in free D:\agent\_work\4\s\src\vctools\crt\asan\llvm\compiler-rt\lib\asan\asan_malloc_win.cpp:110
#1 0x7ffab60649f3  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800749f3)
#2 0x7ffab6064364  (C:\Windows\SYSTEM32\ucrtbased.dll+0x180074364)
#3 0x7ffab6064499  (C:\Windows\SYSTEM32\ucrtbased.dll+0x180074499)
#4 0x7ffab6064b00  (C:\Windows\SYSTEM32\ucrtbased.dll+0x180074b00)
#5 0x7ffab7034aa8 in __scrt_dllmain_uninitialize_c …
```
> [C/C++] Add sanitise build for MSVC and fix issues found.

- aeron-test-support/src/main/java/io/aeron/test/ClusterTestWatcher.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
- build.gradle
- Enables C driver in the slow tests.
- Fixes [java.lang.IndexOutOfBoundsException: index=120 length=1937075275 capacity=1048576](https://github.com/real-logic/aeron/runs/3389075776?check_suite_focus=true) issue that was caused by the reuse of existing `cluster.err` file.
- Updates `UNKNOWN_HOST_FILTER` to handle errors as they are logged by the C driver.
> [C] Enable C driver in slow tests.

- aeron-samples/src/main/java/io/aeron/samples/cluster/tutorial/BasicAuctionClusteredService.java
Following the cluster tutorial, after taking snapshot and a restart, restored auction state is always `Auction{bestPrice=10, currentWinningCustomerId=0}`
```
[381630.026182312] CLUSTER: ELECTION_STATE_CHANGE [34/34]: memberId=1 CANVASS -> FOLLOWER_REPLAY
attemptBid(this=Auction{bestPrice=10, currentWinningCustomerId=0}, price=9385,customerId=10)
```
`onTaskSnapshot` uses wrong index starting from 8(`CUSTOMER_ID_OFFSET`), while `loadSnapshot` read from 0(`SNAPSHOT_CUSTOMER_ID_OFFSET`).
> [Java] Fix snapshot offset error in cluster samples

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-client/src/main/java/io/aeron/CommonContext.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterNodeRestartTest.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/ErrorHandlerTest.java
- aeron-test-support/src/main/java/io/aeron/test/HideStdErrExtension.java
- Setup errorHandlers so that errors are always sent to the configured distinct error log as well as the user specified error handler for Driver, Archive, ConsensusModule, ClusteredServiceContainer, and ClusterBackup.  
- Add stderr output suppression for specific tests.
> Always use error log

- aeron-archive/src/main/cpp/client/ReplayMerge.cpp
Removed stray debugging messages being sent to stdout.
> [C++] Remove debug output from ReplayMerge::resolveReplayPort()

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/PriorityHeapTimerService.java
- aeron-cluster/src/main/java/io/aeron/cluster/PriorityHeapTimerServiceSupplier.java
- aeron-cluster/src/main/java/io/aeron/cluster/WheelTimerServiceSupplier.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/PriorityHeapTimerServiceClusterTimeTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/WheelTimerServiceClusterTimeTest.java
To keep the actual timer services package protected.  Have the WheelTimerServiceSupplier convert from the supplied units to cluster clock units when constructing the timer wheel.
> Add public TimerServiceSupplier classes

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java
- aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java
- aeron-cluster/src/test/java/io/aeron/cluster/RecordingLogTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterToolTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
This PR adds a feature that allows a Cluster to be restarted with the term buffer length and/or MTU changed. This requires truncating an existing recording log to the latest valid snapshot, i.e. Cluster is starting from a snapshot only. The new API to do such truncation is provided via the `ClusterTool` (i.e. `io.aeron.cluster.ClusterTool#truncateRecordingLog` and `truncate-recording-log` command). 
Besides this feature this PR also contains a fix for keeping entries properly sorted in the `RecodingLog`.
> [Java] Add support for changing term buffer length and MTU in the Cluster log.

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/main/java/io/aeron/archive/client/AeronArchive.java
- aeron-client/src/main/java/io/aeron/Aeron.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
This PR fixes #1236:
- Implements missing `toString` on `AeronCluster.Context`, `Aeron.Context`, `AeronArchive.Context`.
- Use single quotes when outputting String values.
- Always put closing curly brace on a new line.
> [Java] Implement missing Context.toString() and align implementations (issue #1236)

- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-samples/src/test/java/io/aeron/samples/archive/RecordingDescriptorCollectorTest.java
If the `minRecordingId` is larger than highest recordingId in the catalogue.  This gives more consistent behaviour and more closely matches the documented API.
> Return -1 instead of throwing in findLastMatchingRecording

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/main/c/aeronmd.h
This allows for the conductor thread to have a different set of transport bindings than the sender and receiver.
> [C] Have separate bindings for conductor.

- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
According to `https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/Election.java#L1041`,  the unit of timestamp should  be the same as ClusterClock.
> Fix timestamp of publishNewLeadershipTerm

- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-samples/src/main/cpp/BasicPublisher.cpp
- aeron-samples/src/main/cpp/BasicSubscriber.cpp
- aeron-samples/src/main/cpp/ExclusiveThroughput.cpp
- aeron-samples/src/main/cpp/Ping.cpp
- aeron-samples/src/main/cpp/PingPong.cpp
- aeron-samples/src/main/cpp/Pong.cpp
- aeron-samples/src/main/cpp/RateSubscriber.cpp
- aeron-samples/src/main/cpp/StreamingPublisher.cpp
- aeron-samples/src/main/cpp/Throughput.cpp
[C/C++] Allow SIGINT to interrupt sample code while waiting for driver connection or waiting on other resources (e.g. images from remote connections).  
[C] Remove udp_channel_transport_bindings.next_binding (unused).
> Sample code interrupts.

- aeron-archive/src/test/java/io/aeron/archive/FailControlResponseListener.java
- aeron-archive/src/test/java/io/aeron/archive/FailRecordingEventsListener.java
- aeron-system-tests/src/test/java/io/aeron/archive/ArchiveTest.java
This PR fixes race conditions in the `io.aeron.archive.ArchiveTest` from the system tests and adds diagnostic output to the `fail` calls.
> [Java] Fix race conditions in the ArchiveTest.

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
Remove extra command prefix when logging in/out commands. Here is an example of a log with extra prefix:
```
[216993.959504] log started 2021-11-24 23:13:28.980+0100
[216993.974496] DRIVER: CMD_IN_ADD_COUNTER [62/62]: ADD_COUNTER 101 [24 0][28 14][1:2]
[216993.974502] DRIVER: CMD_OUT_COUNTER_READY [28/28]: ON_COUNTER_READY 1 31
[216993.974503] DRIVER: CMD_OUT_COUNTER_READY [28/28]: ON_COUNTER_READY 2 32
[216993.974804] DRIVER: CMD_IN_ADD_COUNTER [72/72]: ADD_COUNTER 102 [24 0][28 24][1:3]
[216993.974804] DRIVER: CMD_OUT_COUNTER_READY [28/28]: ON_COUNTER_READY 3 33
[216993.974920] DRIVER: CMD_IN_ADD_SUBSCRIPTION [93/93]: ADD_SUBSCRIPTION 10 aeron:udp?sparse=true|endpoint=localhost:8013 [-1][1:6]
[216993.975053] DRIVER: NAME_RESOLUTION_RESOLVE [40/40]: resolver=csv hostname=localhost …
```
> [C] Remove extra command prefix when logging incoming commands.

- aeron-client/src/main/c/aeron_client.c
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/PublicationParams.java
- aeron-driver/src/main/java/io/aeron/driver/SubscriptionParams.java
- aeron-driver/src/main/java/io/aeron/driver/media/UdpChannel.java
- aeron-samples/src/main/c/basic_subscriber.c
- [C/Java] Extend driver validation of channel re-use to show both channel in the error message when validation fails, i.e. append  `existingChannel=... channel=...` to the end of the message.
- [C] Align error message texts to those of the Java driver.
- [C] Fix string format specifier to be `%.*s`.
> [C/Java] Extend channel re-use validation in the driver to show existing/current channels.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-system-tests/src/test/java/io/aeron/cluster/StalledLeaderLogReplicationClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/SystemTestWatcher.java
And:
- Reset election state correctly after log truncation.
> Ensure that the log publication always has a consistent initial-term-id.

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveContextTests.java
- aeron-client/src/main/java/io/aeron/security/AuthorisationService.java
- aeron-client/src/main/java/io/aeron/security/AuthorisationServiceSupplier.java
- aeron-client/src/test/java/io/aeron/security/AuthorisationServiceTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/EgressPublisher.java
- aeron-cluster/src/main/java/io/aeron/cluster/IngressAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/ControlledEgressListener.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/EgressAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/EgressListener.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/client/EgressAdapterTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
This PR adds new API to `AeronCluster` which allows sending command to the Cluster to trigger a snapshot of the Cluster state. It includes the following:
- New `AuthorisationService` and `AuthorisationServiceSupplier` interfaces.
- `Archive.Context.authorisationServiceSupplier` and `aeron.archive.authorisation.service.supplier` property so that an `AuthorisationServiceSupplier` can be set for the Archive. Default supplier allows any command to be executed.
- `ConsensusModule.Context.authorisationServiceSupplier` and `aeron.cluster.authorisation.service.supplier` property so that an `AuthorisationServiceSupplier` can be set for the ConsensusModule. Default supplier forbids all commands.
- `AdminRequest` and `AdminResponse` messages added to the Cluster wire protocol.
- Support for …
> [Java] Add an admin command to trigger Cluster snapshot.

- aeron-client/src/main/cpp/ChannelUriStringBuilder.h
Fixes for very simple logic errors when translating from Java to C++
> Fixes in ChannelUriStringBuilder.h

- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-archive/src/main/java/io/aeron/archive/DeleteSegmentsSession.java
- aeron-system-tests/src/test/java/io/aeron/archive/ManageRecordingHistoryTest.java
The segment file deletion is now split into two parts:
1. Rename/move the source file by adding a `.del` suffix.
If the rename of any file fails then the whole operation fails as well and the error response is sent to the client.
_Note: when the delete list is being created both the original segment files as well as the renamed files are considered so that the partial deletes can be completed by a subsequent operation._
2. Delete renamed files in the background.
> [Java] Rename then delete the segment files in the Archive.

- aeron-archive/src/test/java/io/aeron/archive/ArchiveTests.java
- aeron-client/src/main/c/aeron_exclusive_publication.h
- aeron-client/src/main/c/concurrent/aeron_logbuffer_descriptor.c
- aeron-client/src/main/c/concurrent/aeron_logbuffer_descriptor.h
- aeron-client/src/main/java/io/aeron/ChannelUriStringBuilder.java
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_ipc_publication.c
- aeron-driver/src/main/c/aeron_ipc_publication.h
- aeron-driver/src/main/c/aeron_loss_detector.c
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/c/aeron_network_publication.h
- aeron-driver/src/main/c/uri/aeron_driver_uri.c
- aeron-driver/src/main/c/uri/aeron_driver_uri.h
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java
- aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
- aeron-driver/src/main/java/io/aeron/driver/PublicationParams.java
- aeron-driver/src/test/java/io/aeron/driver/UntetheredSubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/SpecifiedPositionPublicationTest.java
- aeron-system-tests/src/test/java/io/aeron/archive/ArchiveDeleteAndRestartTest.java
- aeron-system-tests/src/test/java/io/aeron/archive/ArchiveTest.java
- aeron-system-tests/src/test/java/io/aeron/archive/ExtendRecordingTest.java
- aeron-test-support/src/main/java/io/aeron/test/RandomWatcher.java
- aeron-test-support/src/main/java/io/aeron/test/Tests.java
- Allows initialTermId, termId, and termOffset for concurrent publications and use those fields for matching concurrent publications (C and Java Drivers).
- If values are not specified with subsequent publications, then addition of publications is allowed.
- Make C driver mtu and termLength parameter matching consistent with the Java driver.
> Extend recording concurrent publications

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-system-tests/src/test/java/io/aeron/cluster/RacingCatchupClusterTest.java
Separate timestamps of AppendPosition into send and update, use send to track resends and update to track/timeout progress.
> Ensure catchup times out with lack of progress

- aeron-client/src/main/c/CMakeLists.txt
- aeron-driver/src/main/c/CMakeLists.txt
Add -latomic as a link dep on aeron_client & aeron_driver. This is required when building on ARM with clang.
Eg. cmake -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 ../..
> fix build on ARM with clang

- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-archive/src/main/java/io/aeron/archive/ReplicationSession.java
- aeron-client/src/main/java/io/aeron/ChannelUri.java
- aeron-client/src/test/java/io/aeron/ChannelUriTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/DynamicJoin.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogPublisher.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogReplication.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
This PR makes it possible to configure `interface` params for _all_ of the Cluster channels. To that end it:
- Replaces all of the ad hoc channels used for defining destinations with the call to `ChannelUri#createDestinationUri`.
- Adds two new configuration properties `aeron.cluster.follower.catchup.channel` and `aeron.cluster.leader.archive.control.channel`. The former is used to create the replay channel when doing a catch up on the follower node. And the latter is used for creating a control request channel to the leader archive.
- Adds an `egressChannel` configuration option to the `ConsensusModule` which is using the same configuration property as the `AeronCluster` (i.e. `aeron.cluster.egress.channel`). When the `egressChannel` is not defined then response channel from the leader …
> [Java] Cluster interface config.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
Split catchupPosition into catchupJoinPosition - based on logPosition from new leadership term and catchCommitPosition - based on commit position messages received from the leader during catchup.  Use catchupCommitPosition as the limitPosition for processing messages from the LogAdapter during catchup.  Use the max of the two to determine that the follower is close enough to join the live stream and leave the catchup state.
> Split catchupPosition into catchupJoinPosition and catchupCommitPosition

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterTerminationException.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/ClusterTests.java
I also added a message to the exception.  This will end up in the stack trace, where we'd like to be able to tell whether it was an expected termination or not.
> [Java] Add a flag to ClusterTerminationException to say whether it was expected or not

- aeron-driver/src/main/c/aeron_data_packet_dispatcher.c
- aeron-driver/src/main/c/aeron_driver_receiver.c
- aeron-driver/src/main/c/aeron_publication_image.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.h
- aeron-driver/src/test/c/CMakeLists.txt
- aeron-driver/src/test/c/aeron_c_multi_destination_test.cpp
- aeron-driver/src/test/c/aeron_c_system_test.cpp
- aeron-driver/src/test/c/aeron_publication_image_test.cpp
- aeron-driver/src/test/c/aeron_test_udp_bindings.h
Looping is already covered at a higher point in the call stack (generally by connection per image).  Use specific sends for setup eliciting SM so that only the correct destination is targeted.
> [C] Remove loop through destinations nested within receive_channel_endpoint_send

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_conductor.h
- aeron-driver/src/main/c/aeron_driver_receiver.c
- aeron-driver/src/main/c/aeron_driver_receiver_proxy.c
- aeron-driver/src/main/c/aeron_driver_receiver_proxy.h
- aeron-driver/src/main/c/aeron_publication_image.c
- aeron-driver/src/main/c/aeron_publication_image.h
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/test/c/aeron_driver_conductor_network_test.cpp
- Fix bug where 0 was used instead of index when iterating over destinations.
- Move method into tests that was only used by tests.
- Include two pointers on image for the endpoint, one to be used by the receiver the other to be used by the conductor.
> Reduce sharing on image endpoint

- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
Reports an error if timestamps are not supported on the platform Aeron is running on, but swallows it and continues.
> [C] Warning on failure to setup media timestamps

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/DynamicMembershipTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
Remove replicationCommitPosition which was used to verify a leader had committed a position equal or higher than the log replicated position. This is not required as replication should only proceed to the end of previous term which will already be committed. It allows dynamic nodes to work more cleanly with log replication as they don't receive commit position messages until after catch up and they have offically joined the cluster.
> Prevent timeout warnings with dynamic nodes and log replication

- aeron-client/src/main/c/concurrent/aeron_mpsc_rb.c
- aeron-client/src/main/c/concurrent/aeron_mpsc_rb.h
- aeron-client/src/main/c/concurrent/aeron_rb.h
- aeron-client/src/main/c/concurrent/aeron_spsc_rb.c
- aeron-client/src/main/c/concurrent/aeron_spsc_rb.h
- aeron-client/src/test/c/concurrent/aeron_mpsc_rb_test.cpp
- aeron-client/src/test/c/concurrent/aeron_spsc_rb_test.cpp
This PR updates the C implementations of the one to one and one to many ring buffers and aligns them with the Java:
- Add a notion of minimum capacity which for mspc is one record header and for spsc is two record headers as it does pre-zeroing.
- Change capacity validation and calculation of the maxMessageLength.
- Allow fitting a message at the end of the buffer for spsc without padding.
> [C] Align ring buffer implementations with Java.

- aeron-archive/src/main/cpp/client/AeronArchive.h
- aeron-archive/src/main/cpp/client/ArchiveConfiguration.h
- aeron-archive/src/main/cpp/client/ArchiveProxy.cpp
- aeron-archive/src/main/cpp/client/ArchiveProxy.h
- aeron-archive/src/test/cpp/AeronArchiveTest.cpp
Also add the fluent params objects.
> Support Max I/O Length on a per archive request basis in the C++ API

- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotListener.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotPrinter.java
- aeron-cluster/src/main/java/io/aeron/cluster/PendingServiceMessageTracker.java
- aeron-samples/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotPendingServiceMessagesPatch.java
- aeron-samples/src/test/java/io/aeron/cluster/ConsensusModuleSnapshotPendingServiceMessagesPatchTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
This PR adds a new tool `ConsensusModuleSnapshotPendingServiceMessagesPatch` that can fix consensus module snapshot state if the divergence in pending service messages is detected.
> [Java] Fix pending service messages snapshot state.

- aeron-client/src/main/c/util/aeron_fileutil.c
- aeron-client/src/main/c/util/aeron_fileutil.h
- aeron-client/src/test/c/util/aeron_fileutil_test.cpp
**Note: This PR changes the signatures of two functions, i.e. `aeron_mmap` and `aeron_ftruncate`**.
> [C] Handle log buffer files with `term_length == AERON_LOGBUFFER_TERM_MAX_LENGTH` on Windows.

- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/main/java/io/aeron/archive/ReplicationSession.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
- aeron-samples/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotPendingServiceMessagesPatch.java
- aeron-system-tests/src/test/java/io/aeron/archive/ReplicateRecordingTest.java
This PR changes how the `replicate` Archive API will treat an empty destination recording (i.e. whose `startPosition == stopPosition`). In such a case the source recording will completely overwrite such recording.
> [Java] Allow `replicate` to overwrite an empty recording.

- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
Aliases to easily differentiate between different log subscriptions.
- Archive: `|alias=log`
- Consensus module: `|alias=log-cm`
- Service container(s): `|alias=log-sc-0`
> Differentiate aliases for consensus module/service container subscriptions.

- aeron-client/src/test/java/io/aeron/PublicationTest.java
Avoid a core dump due to unaligned memory access (putLongOrdered)
> Align term buffer in PublicationTest

- aeron-client/src/main/java/io/aeron/AeronCounters.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusPublisher.java
- aeron-cluster/src/main/java/io/aeron/cluster/IngressAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogSourceValidator.java
- aeron-cluster/src/main/java/io/aeron/cluster/PublicationGroup.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
- aeron-cluster/src/test/java/io/aeron/cluster/LogSourceValidatorTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/PublicationGroupTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterBackupTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
- The leader will send a redirect in response to backup queries (indicating that the leader should not be used).
- ClusterBackup will try a different node in response to a redirect
- Create a separate collection of sessions for backup requests & auth ("backup sessions" vs "user sessions").  Process backup sessions on both leader and follower.  Do not persist backup sessions.
- Randomise the starting node for backup queries in the ClusterBackup.
> Handle backup queries from cluster followers only

- aeron-client/src/main/java/io/aeron/AeronCounters.java
- aeron-client/src/test/java/io/aeron/AeronCountersTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleStateExport.java
- aeron-cluster/src/main/java/io/aeron/cluster/ServiceProxy.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ServiceAdapter.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
- aeron-cluster/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ClusteredServiceAgentTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/CountersAnswer.java
- aeron-test-support/src/main/java/io/aeron/test/SystemTestWatcher.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- Define structures to import state into the ConsensusModule.
- Support starting the ConsensusModuleAgent from existing state.
- Add more Standby/TransitionModule counters.
- Small testing updates and utilities.
> Support importing ConsensusModule state to support transitioning.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotTaker.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ServiceSnapshotTaker.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/SnapshotTaker.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleSnapshotTakerTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ServiceSnapshotTakerTest.java
This PR updates `ConsensusModuleSnapshotTaker` and `ServiceSnapshotTaker` to use choose between `tryClaim` and offer into the snapshot publication depending on the size of the data.
> [Java] Handle snapshot messages bigger than the maxPayloadSize when taking a snapshot of the Cluster metadata.

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterMember.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterMemberTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterNetworkTopologyTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestClusterClock.java
The transition from `CANVASS` to `NOMINATE` and from `CANDIDATE_BALLOT` to `LEADER_LOG_REPLICATION` in case the corresponding vote/candidacy check is not unanimous is done with a timeout that is based on the time of the last message received from the leader. Which is tracked upon receiving the `onCommitPosition` and `onNewLeadershipTerm` messages.
The delay is necessary to prevent the non-eligible majority of forming a quorum and electing a new leader.
> [Java] Delay election state transitions if there is an active leader.

- aeron-archive/src/main/cpp/client/RecordingPos.h
- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-archive/src/main/java/io/aeron/archive/ArchiveCounters.java
- aeron-archive/src/main/java/io/aeron/archive/status/RecordingPos.java
- aeron-archive/src/test/cpp/AeronArchiveTest.cpp
- aeron-archive/src/test/java/io/aeron/archive/ArchiveContextTest.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveCountersTest.java
- aeron-archive/src/test/java/io/aeron/archive/status/RecordingPosTest.java
- aeron-client/src/main/cpp/concurrent/CountersReader.h
- Adds a notion of `archiveId` (`long`) which can be set on the `Archive.Context` programmatically or via the system property `aeron.archive.id`.
If not set then it defaults to `Aeron.clientId()` of the corresponding `Aeron` instance.
- Uses `archiveId` to make Archive-specific counters unique, i.e. adds `archiveId` to the key and label (i.e. `` similar to what `ClusterCounters` does.
- Changes `RecordingPos` to include `archiveId` in the key and label.
Here a sample of how the counters look like after the change:
```java
...
33:           21,365,164 - archive-conductor max cycle time in ns - archiveId=1
34:                    0 - archive-conductor work cycle time exceeded count: threshold=1000000000ns - archiveId=1
35:            2,268,616 - …
```
> [Java] Make Archive counters unique.

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
I think it's more consistent with the [Java driver implementation](https://github.com/real-logic/aeron/blob/f63401abf37c6fff3fea6b4af45a540c13e03bb7/aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java#L487) and should fix the issue #1393 1393.
> Only try unblocking if producer is ahead for liveness_timeout

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveContextTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ClusterMarkFileTest.java
- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/java/io/aeron/driver/Configuration.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/test/java/io/aeron/driver/MediaDriverContextTest.java
- Adds validation for the CnC file length and the length of the components.
- Sets the upper limit for the `counterValuesBufferLength` to **500MB**.
- Adds length validations to the Archive and the Cluster.
> [Java/C] CnC file length validation.

- aeron-driver/src/main/c/aeron_driver_context.c
This stops them being incorrectly set to 0 by aeron_config_parse_uint32 when comparing against int32 0
Current behaviour will always set the value to 0 if the environment variable is specified.
> Set max of resource free queue length and resource free limit to INT32_MAX

- aeron-archive/src/main/java/io/aeron/archive/ArchiveMigration_0_1.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/Election.java
- aeron-cluster/src/main/java/io/aeron/cluster/NodeStateFile.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-node-state-codecs.xml
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/NodeStateFileTest.java
- aeron-system-tests/src/test/java/io/aeron/TimestampingSystemTest.java
- build.gradle
- Introduce NodeStateFile.
- Add support for storing candidateTermId NodeStateFile.
- Migrate candidateTermId from the cluster mark file
- Use NodeStateFile in Election to trace candidateTermId.
> Node State File with persistent candidateTermId.

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
- aeron-archive/src/main/java/io/aeron/archive/ArchiveMarkFile.java
- aeron-archive/src/main/java/io/aeron/archive/client/AeronArchive.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveContextTest.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java
- aeron-system-tests/src/test/java/io/aeron/archive/ReplicateRecordingTest.java
This PR adds a new configuration property `aeron.archive.control.channel.enabled` which allows disabling control channel (UDP) when set to `false`. In which case the Archive only listens to the IPC requests.
Setting this property to `false` also requires that the `Archive.Context.archiveClientContext.controlResponseChannel` is set as it won't be derived from the `Archive.Context.controlChannel`.
Fixes #1416.
> [Java] Allow running Archive in IPC-only mode.

- aeron-client/src/main/cpp/ClientConductor.h
Makes the keepalive timeout exception consistent with implementation in aeron_client_conductor_check_liveness
https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/c/aeron_client_conductor.c#L381-L393
> [C++] Make MediaDriver keepalive exception consistent

- aeron-client/src/main/cpp/Image.h
- aeron-client/src/main/cpp/Subscription.h
This is especially useful if
* the fragment handler is a `std::function` or some other type that owns heap memory
* or the fragment handler is only movable, not copyable
> [C++] std::forward fragment handlers to avoid unnecessary copies

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotListener.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotPrinter.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotTaker.java
- aeron-cluster/src/main/java/io/aeron/cluster/NodeStateFile.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-node-state-codecs.xml
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleSnapshotTakerTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/NodeStateFileTest.java
- aeron-samples/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotPendingServiceMessagesPatch.java
- aeron-samples/src/test/java/io/aeron/cluster/ConsensusModuleSnapshotPendingServiceMessagesPatchTest.java
- Support dynamically sized records in the node state file.  Handle this by moving trailing records up/down the file as required.
- Add a footer record for tracking the end of the file.
- Add cluster members record.
- Remove cluster member state from the consensus module snapshot.
> Store cluster membership changes in node state file

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_receiver.c
- aeron-driver/src/main/c/aeron_driver_receiver.h
- aeron-driver/src/main/c/aeron_driver_receiver_proxy.c
- aeron-driver/src/main/c/aeron_driver_receiver_proxy.h
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.h
Currently if create_publication_image fails:
1. It can fail silently without actually committing errors.
2. It will leave an entry in the data_packet_dispatcher for that session/stream in INIT_IN_PROGRESS state, for as long as there is a subscriber. This stops any potential for this stream/session to be subscribed to, even if the error was temporary.
This change removes the dead entry from the image_by_session_id_map in the packet_dispatcher, and ensures errors are logged if a failure is hit.
> [C] Handle failed create_publication_image

- aeron-driver/src/main/c/aeron_publication_image.c
- aeron-driver/src/test/c/aeron_c_system_test.cpp
Seems to have been broken by this commit: https://github.com/reissGRVS/aeron/commit/605a71feac0d101fb5006c52aea48e6ea1a844ec#r104348901
The cool down entry was being inserted after the remove attempt.
Remove attempt via aeron_driver_conductor_image_transition_to_linger https://github.com/real-logic/aeron/blob/f94e8e899ff5900556d7e6c5bab65fcd18784f89/aeron-driver/src/main/c/aeron_driver_conductor.c#L1351
Insert via aeron_driver_receiver_proxy_on_remove_publication_image->aeron_driver_receiver_on_remove_publication_image->aeron_receive_channel_endpoint_on_remove_publication_image->aeron_data_packet_dispatcher_remove_publication_image
https://github.com/real-logic/aeron/blob/f94e8e899ff5900556d7e6c5bab65fcd18784f89/aeron-driver/src/main/c/aeron_data_packet_dispatcher.c#L262
> [C] Fix rejoin logic by swapping cool down map insertion and removal.

- README.md
Aeron Cookbook is now a part of Aeron.io, with more than one contributor.
> Update on Aeron Cookbook

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/uri/aeron_driver_uri.c
- aeron-driver/src/main/c/uri/aeron_driver_uri.h
- aeron-system-tests/src/test/java/io/aeron/test/driver/TestMediaDriverTest.java
- aeron-test-support/src/main/java/io/aeron/test/InterruptingTestCallback.java
- aeron-test-support/src/main/java/io/aeron/test/SystemTestConfig.java
- aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
- build.gradle
- Add a system property to specify that the system tests should wait for the send and receive endpoint counters to be removed before stopping the media driver.
- Add minimum timeout for InterruptingTestCallback if tests will wait for the counters to close before shutting down the media driver.
- Fix memory leak when creating endpoints with MTUs that are too large for the socket sndbuf.
> Wait for counters to support memory santization

- aeron-agent/src/main/java/io/aeron/agent/DriverComponentLogger.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/DriverInterceptor.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventLoggerTest.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveContextTest.java
- aeron-client/src/main/java/io/aeron/CounterProvider.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ClusteredServiceContainerContextTest.java
- aeron-driver/src/main/java/io/aeron/driver/Configuration.java
- aeron-driver/src/main/java/io/aeron/driver/DefaultNameResolver.java
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/DriverNameResolver.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/io/aeron/driver/NameResolver.java
- aeron-driver/src/main/java/io/aeron/driver/TimeTrackingNameResolver.java
- aeron-driver/src/main/java/io/aeron/driver/status/DutyCycleStallTracker.java
- aeron-driver/src/main/java/io/aeron/driver/status/SystemCounterDescriptor.java
- aeron-driver/src/test/java/io/aeron/driver/DefaultNameResolverTest.java
- aeron-driver/src/test/java/io/aeron/driver/DriverConductorTest.java
- aeron-driver/src/test/java/io/aeron/driver/IpcPublicationTest.java
- aeron-driver/src/test/java/io/aeron/driver/MediaDriverTest.java
- aeron-driver/src/test/java/io/aeron/driver/TimeTrackingNameResolverTest.java
- aeron-driver/src/test/java/io/aeron/driver/status/DutyCycleStallTrackerTest.java
- aeron-test-support/src/main/java/io/aeron/test/driver/RedirectingNameResolver.java
This PR adds a capability to track the execution of the `NameResolver#resolve` and `NameResolver#lookup` methods via a new set of counters. It also extends the existing logging events with the `durationNs` field and adds logging for the lookup method, e.g.:
```bash
[43598.051268] DRIVER: NAME_RESOLUTION_LOOKUP [74/74]: resolver=RedirectingNameResolver durationNs=6430 name=127.0.0.1:24326 isReLookup=false resolvedName=127.0.0.1:24326
[43598.051826] DRIVER: NAME_RESOLUTION_RESOLVE [57/57]: resolver=RedirectingNameResolver durationNs=21460 name=127.0.0.1 isReResolution=false address=127.0.0.1
```
There is also a new method `NameResolver#init(CounterProvider)` which was added to replace the `NameResolver#init(MediaDriver.Context)`. The latter could only be used in the driver while the former …
> [Java] Name resolution execution time tracking.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotTaker.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleSnapshotTakerTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ServiceIpcIngressMessageTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/ClusterTests.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
When the `PendingServiceMessageTracker` buffer is empty, but the `nextServiceSessionId` is lower that what it should be, this indicates that the follower may not have queued a service IPC message correctly.  This corrects the value at the point of snapshot and logs an error to alert the user to the potential non-determinism.  This avoids a fatal exception on startup.
> Correct nextServiceSessionId on snapshot

- aeron-driver/src/main/c/aeron_min_flow_control.c
I think if this is reusing the index of a previously removed receiver eos_flagged can be left as true. This leads to immediate removal of the new receiver if `aeron_min_flow_control_strategy_on_idle` is called prior to receiving a second SM for this receiver.
> Reset eos_flagged when adding receiver

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-client/src/main/java/io/aeron/security/SimpleAuthenticator.java
- aeron-client/src/main/java/io/aeron/security/SimpleAuthorisationService.java
- aeron-client/src/test/java/io/aeron/security/SimpleAuthenticatorTest.java
- aeron-client/src/test/java/io/aeron/security/SimpleAuthorisationServiceTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-samples/src/main/java/io/aeron/samples/archive/SampleAuthenticator.java
- aeron-samples/src/main/java/io/aeron/samples/security/SimpleAuthenticator.java
- aeron-samples/src/main/java/io/aeron/samples/security/SimpleAuthorisationService.java
- aeron-samples/src/test/java/io/aeron/samples/security/SimpleAuthenticatorTest.java
- aeron-samples/src/test/java/io/aeron/samples/security/SimpleAuthorisationServiceTest.java
- build.gradle
- Add Authentication and Authorisation services that allow for simple configuration of principals and roles.
- Add Javadoc that enumerates the protocol, action and types that are relevant to authorisation calls.
- Prevent memory leaks in the SampleAuthenticator.
> Authentication services

- aeron-agent/src/main/java/io/aeron/agent/DriverComponentLogger.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventCode.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventDissector.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventEncoder.java
- aeron-agent/src/main/java/io/aeron/agent/DriverEventLogger.java
- aeron-agent/src/main/java/io/aeron/agent/DriverInterceptor.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventDissectorTest.java
- aeron-agent/src/test/java/io/aeron/agent/DriverEventLoggerTest.java
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.h
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/DriverNameResolver.java
- aeron-driver/src/main/java/io/aeron/driver/TimeTrackingNameResolver.java
- aeron-driver/src/test/c/agent/aeron_driver_agent_test.cpp
- aeron-system-tests/src/test/java/io/aeron/NameReResolutionTest.java
* Host name is resolved only once.
* Host name resolution time is tracked via name resolution duty cycle tracker.
* Agent logging was added around host name resolution.
* For Java the name resolution happens after the time was initialized, i.e. the pause will be reflected in a DriveConductor's duty cycle counter.
* C driver name resolution logging fixes.
> [C/Java] Changes to host name resolution upon media driver startup.

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ClusteredServiceContainerContextTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterBackupContextTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterToolTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
Allows for the consensus module, clustered service container and cluster backup to store their mark files in a location other than in the cluster directory (e.g. on a in-memory file system).  This allows for improved performance due to reducing I/O for writing the timestamp into the mark file.
> Cluster relocatable mark files

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
There was no separator between correlation id and error code.
> [C] Fix CMD_OUT_ERROR log format.

- aeron-client/src/main/c/util/aeron_error.c
- aeron-client/src/test/c/util/aeron_error_test.cpp
Noticed that sometimes "no error" is reported instead of the actual error. If you clear and then append without setting first, then modifications will be done at previous offset and will be invisible.
> [C] Fix aeron_err_clear().

- aeron-client/src/main/c/util/aeron_netutil.c
- aeron-client/src/main/c/util/aeron_netutil.h
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/media/aeron_udp_channel.c
- aeron-driver/src/main/c/media/aeron_udp_channel.h
- aeron-driver/src/main/java/io/aeron/driver/media/UdpChannel.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
- aeron-system-tests/src/test/java/io/aeron/MultiSubscriberTest.java
- aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java
- Allow a channel URI to contain both tags and endpoint parameters even if there is already a send or receive channel endpoint for the tag.
- For existing endpoints, check that the control and endpoint values are the same and reject if they do not match.
- Potential Fix for #1498.
> Support specifying endpoints and tags in the same URI

- aeron-driver/src/test/c/aeron_c_system_test.cpp
shouldAddMdsSubscription is a duplicate of shouldAddPublicationAndSubscription.
There are MDS tests in aeron_c_multi_destination_test.cpp.
> [C] Remove duplicated test.

- aeron-client/src/main/c/aeron_image.c
- aeron-client/src/test/c/aeron_image_test.cpp
subscriber_position_id was passed to aeron_image_create(), but never used.
> [C] Populate client image subscriber_position_id.

- aeron-client/src/main/c/concurrent/aeron_counters_manager.c
I find accessing a field with a different field quite confusing.
> [C] Refactor aeron_counters_reader_counter_type_id().

- aeron-driver/src/main/c/aeron_driver_conductor.c
When looking at AeronStat of a C media driver, noticed that a spy subscription doesn't have the aeron-spy: prefix like in the Java driver. Turns out we incorrectly copy the channel into the link - starting after the prefix. Also, the copy uses the full length potentially trying to access data out of bound. This was inconsistent with MDS code which is using the full channel for spies.
Image unavailability callbacks now get the full channel with prefix.
> [C] Fix spy subscription channel.

- aeron-client/src/main/c/aeron_client_conductor.c
- aeron-client/src/main/c/aeron_client_conductor.h
- aeron-client/src/main/c/aeron_image.c
- aeron-client/src/main/c/aeron_image.h
- aeron-client/src/main/c/collections/aeron_array_to_ptr_hash_map.h
- aeron-client/src/test/c/aeron_image_test.cpp
- aeron-client/src/test/c/aeron_subscription_test.cpp
- aeron-client/src/test/c/collections/aeron_array_to_ptr_hash_map_test.cpp
- aeron-driver/src/test/c/aeron_c_system_test.cpp
On the client side, aeron_image_t represents a link between a subscription and an image. There can be multiple subscriptions using a single image, which means there can be multiple aeron_image_t objects with the same correlation_id. Using the correlation_id as the map key means only the last object is kept, leading to a potential memory leak and invalid image unavailability notifications. This change makes the map keyed on both correlation_id and subscription_registration_id which uniquely identify aeron_image_t objects.
Changed aeron_int64_to_ptr_hash_map_put to replace the key as well, which makes more sense, especially when using keys embedded in values.
> Fix C client when one image matches multiple subscriptions

- aeron-archive/src/test/java/io/aeron/archive/ArchiveCountersTest.java
This makes it large enough to handle counter names that include the 'guilty' suffix on the git hash
> [Java] Increase the buffer size for counter names.

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/main/java/io/aeron/archive/CatalogIndex.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolCliTest.java
and add a `describe-all` command which shows valid and invalid recordings.
This makes `describe` consistent with the behaviour of `describe [recording-id]`, which does not show invalidated recordings. The output of `describe-all` indicates whether a recording is valid or not.
> [Java] Exclude invalid recordings from `ArchiveTool describe`... 

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_name_resolver.c
- aeron-driver/src/main/c/media/aeron_receive_destination.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.h
- aeron-driver/src/main/c/media/aeron_udp_channel_transport_bindings.h
- aeron-driver/src/test/c/aeron_network_publication_test.cpp
- aeron-driver/src/test/c/aeron_test_udp_bindings.h
Add mtu_length as a parameter to be passed to UDP bindings. This makes it easier for bindings to validate the MTU length in use by Aeron.
> [C] Introduce a parameters structure for aeron_udp_channel_transport_init

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/main/java/io/aeron/archive/Catalog.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveMigrationUtils.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolTests.java
- aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
These provide a way to patch the catalog in an emergency.
Added the following ArchiveTool commands:
```
mark-invalid <recordingId>: marks a recording as invalid.
mark-valid <recordingId>: marks a previously invalidated recording as valid.
```
> Add ArchiveTool mark-valid, mark-invalid commands.

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_udp_channel.c
- aeron-driver/src/main/c/media/aeron_udp_channel.h
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/media/SendChannelEndpoint.java
- aeron-driver/src/main/java/io/aeron/driver/media/UdpChannel.java
- aeron-driver/src/test/c/aeron_c_multi_destination_test.cpp
- aeron-driver/src/test/java/io/aeron/driver/UdpChannelTest.java
- aeron-driver/src/test/java/io/aeron/driver/media/WildcardPortManagerTest.java
- aeron-system-tests/src/test/java/io/aeron/ChannelValidationTest.java
- aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
- aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java
- aeron-system-tests/src/test/java/io/aeron/ResolvedEndpointSystemTest.java
- aeron-system-tests/src/test/java/io/aeron/WildcardPortManagerSystemTest.java
- aeron-system-tests/src/test/java/io/aeron/archive/ReplicateRecordingTest.java
This tidies up some of the validation around control-mode and control address.  It now requires that `control-mode=dynamic` have a control address and also be explicitly stated.  Just specifying a control address does not imply `control-mode=dynamic`.  Now specifying a `control` address requires a `control-mode` or an `endpoint`.  If an endpoint is specified then this is a plain channel with an explicit control address (i.e. not a wildcard).
It also validates how control-mode can be specified with respect to the use of tags.  I.e. the control-mode can be omitted or must match the control-mode of any existing channel with the same tag.
> Stricter validation on control addresses

- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-system-tests/src/test/java/io/aeron/CounterReferencesTest.java
This ports to the Java media driver the following change: 579730d9c ("[C] set reference id of sub-pos to registration id of the image/publication.")
Also adds a system test covering both.
> [Java] Set reference id of sub-pos to registration id of the image/publication

- aeron-client/src/main/java/io/aeron/AeronCounters.java
- aeron-client/src/main/java/io/aeron/ClientConductor.java
- aeron-client/src/test/java/io/aeron/AeronCountersTest.java
- aeron-samples/src/main/java/io/aeron/samples/CncFileReader.java
- aeron-samples/src/main/java/io/aeron/samples/SamplesUtil.java
- aeron-system-tests/src/test/java/io/aeron/ClientContextTest.java
- aeron-system-tests/src/test/java/io/aeron/driver/SystemCountersTest.java
- aeron-test-support/src/main/java/io/aeron/test/SystemTestWatcher.java
- aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
- buildSrc/src/main/java/io/aeron/build/GithubUtil.java
- cppbuild/centos/Dockerfile
- cppbuild/rocky/Dockerfile
- Add client version to the `client-heartbeat` counter.
- Fix dirty repo detection on the Java side, i.e. ignore untracked files.
- Add system counters tests which checks that the counter labels are similar across different MD implementations.
> [Java] Add client version info to the `client-heartbeat` counter.

- aeron-samples/src/main/c/aeron_stat.c
AeronStat was effectively ignoring `-u` and incorrectly using `-t` instead.
> [C] Make AeronStat respect update interval option.

- aeron-client/src/main/java/io/aeron/AeronCounters.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/SnapshotDurationTracker.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
This PR introduces a set of counters that enable monitoring of snapshot duration within Cluster's Consensus Module:
* `AeronCounters#CLUSTER_CONSENSUS_MODULE_MAX_SNAPSHOT_DURATION_TYPE_ID` to track maximum snapshot duration.
* `AeronCounters#CLUSTER_CONSENSUS_MODULE_SNAPSHOT_DURATION_THRESHOLD_EXCEEDED_TYPE_ID` to track number of times a predefined threshold value (see below) has been exceeded.
Threshold value can be set via `aeron.cluster.consensus.module.snapshot.threshold` property or via `io.aeron.cluster.ConsensusModule.Context#snapshotDurationThresholdNs(long)`.
> [Java] Introduce SnapshotDurationTracker

- aeron-client/src/main/c/aeronc.h
- aeron-client/src/main/cpp/ExclusivePublication.h
- aeron-client/src/main/cpp/Publication.h
- aeron-client/src/main/cpp_wrapper/ExclusivePublication.h
- aeron-client/src/main/cpp_wrapper/FragmentAssembler.h
- aeron-client/src/main/cpp_wrapper/Publication.h
- aeron-client/src/main/java/io/aeron/Publication.java
- aeron-client/src/test/cpp_wrapper/SystemTest.cpp
- Fix wrapper's [Exclusive]Publication.maxPayloadLength().
- Fix wrapper's FragmentAssembler.
> C++ wrapper fixes

- aeron-driver/src/main/c/aeronmd.h
I have the following error when compiling with `-Werror` the aeron-driver:
```
aeron-src/aeron-driver/src/main/c/aeronmd.h:90:1: error: 'size_t' does not name a type
+cpp-bindings |    90 | size_t aeron_driver_context_get_to_conductor_buffer_length(aeron_driver_context_t *context);
+cpp-bindings |       | ^~~~~~
```
I know we can include the `stddef` header in a different file and make it work, but what do you think about including it in the file we are using the `size_t` type ?
> Include missing header stddef.h to use size_t

- aeron-client/src/main/java/io/aeron/BufferBuilder.java
- aeron-client/src/main/java/io/aeron/ConcurrentPublication.java
- aeron-client/src/main/java/io/aeron/ControlledFragmentAssembler.java
- aeron-client/src/main/java/io/aeron/ExclusivePublication.java
- aeron-client/src/main/java/io/aeron/FragmentAssembler.java
- aeron-client/src/main/java/io/aeron/ImageControlledFragmentAssembler.java
- aeron-client/src/main/java/io/aeron/ImageFragmentAssembler.java
- aeron-client/src/main/java/io/aeron/Publication.java
- aeron-client/src/main/java/io/aeron/logbuffer/Header.java
- aeron-client/src/main/java/io/aeron/logbuffer/LogBufferDescriptor.java
- aeron-client/src/test/java/io/aeron/BufferBuilderTest.java
- aeron-client/src/test/java/io/aeron/FragmentAssemblerTest.java
- aeron-client/src/test/java/io/aeron/logbuffer/HeaderTest.java
- aeron-client/src/test/java/io/aeron/logbuffer/LogBufferDescriptorTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/LogAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/BoundedLogAdapter.java
- aeron-system-tests/src/test/java/io/aeron/FragmentedMessageTest.java
- aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
Re-assemble header of the fragmented message so that it represents a complete message, i.e.:
* Compute `frameLength` for the entire message.
* Set the `BEGIN_FRAG_FLAG` on the `flags` to mark message as unfragmented.
* Preserve `termOffset`, `termId`, `sessionId`, `streamId` and `reserevedValue` of the first fragmented header.
> [Java] Re-assemble header for fragmented messages.

- aeron-agent/src/main/java/io/aeron/agent/DriverEventCode.java
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/c/aeron_network_publication.h
- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/agent/aeron_driver_agent.h
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.h
- aeron-driver/src/test/c/agent/aeron_driver_agent_test.cpp
> Add C driver logging for send_nak_message and resend

- aeron-driver/src/main/c/CMakeLists.txt
When building a package, CMake will strip the rpath by default. This means that when you extract it and try to run aeronmd, it won't work:
```
$ readelf -d ./aeron-1.44.0-Linux/bin/aeronmd | grep 'R.*PATH'
$ ./aeron-1.44.0-Linux/bin/aeronmd
./aeron-1.44.0-Linux/bin/aeronmd: error while loading shared libraries: libaeron_driver.so: cannot open shared object file: No such file or directory
```
This change sets rpath for the packaged aeronmd binary:
```
$ readelf -d ./aeron-1.44.0-Linux/bin/aeronmd | grep 'R.*PATH'
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
$ ./aeron-1.44.0-Linux/bin/aeronmd
^CShutting down driver...
```
> [Build] Set aeronmd rpath in the generated package.

- aeron-client/src/main/c/aeron_client.c
- aeron-client/src/main/cpp_wrapper/Aeron.h
- aeron-client/src/test/cpp_wrapper/SystemTest.cpp
Use the C client close handler to ensure that the client conductor thread drains before destructing the Aeron resources in the C++ wrapper.
> Prevent sanitiser errors when shutting down subscription and client in quick succession

- aeron-agent/src/test/java/io/aeron/agent/EventConfigurationTest.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-driver/src/main/java/io/aeron/driver/ClientCommandAdapter.java
- aeron-driver/src/main/java/io/aeron/driver/CommandProxy.java
- aeron-driver/src/main/java/io/aeron/driver/Configuration.java
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/DriverConductorProxy.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/io/aeron/driver/Receiver.java
- aeron-driver/src/main/java/io/aeron/driver/ReceiverProxy.java
- aeron-driver/src/main/java/io/aeron/driver/Sender.java
- aeron-driver/src/main/java/io/aeron/driver/SenderProxy.java
- aeron-driver/src/main/java/io/aeron/driver/media/SocketAddressParser.java
- aeron-driver/src/main/java/io/aeron/driver/media/UdpChannel.java
- aeron-driver/src/test/java/io/aeron/driver/DriverConductorTest.java
- aeron-driver/src/test/java/io/aeron/driver/IpcPublicationTest.java
- aeron-driver/src/test/java/io/aeron/driver/MediaDriverContextTest.java
- aeron-driver/src/test/java/io/aeron/driver/MediaDriverTest.java
- aeron-driver/src/test/java/io/aeron/driver/ReceiverTest.java
- aeron-driver/src/test/java/io/aeron/driver/SenderTest.java
- aeron-driver/src/test/java/io/aeron/driver/UdpChannelTest.java
- aeron-driver/src/test/java/io/aeron/driver/media/SocketAddressParserTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/MultiModuleSharedDriverTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
This PR implements asynchronous DNS resolution in the Java MediaDriver including:
* Client commands: `ADD_RCV_DESTINATION` (spy and network), `REMOVE_RCV_DESTINATION`, `ADD_SUBSCRIPTION` (spy and network), `ADD_PUBLICATION`, `ADD_DESTINATION` and `REMOVE_DESTINATION`.
* Address re-resolution (`onReResolveControl` and `onReResolveEndpoint`) which are triggered by the receiver and sender threads respectively.
* `ConsensusModule#connectIngress` - check for multicast address is now done without calling `NameResolver`.
What is not included:
* Initial host name resolution, i.e. `DriverConductor#onStart`.
* `DriverNameResolver` - bootstrap neighbor resolution and duty cycle.
> [Java] Async DNS resolution.

- aeron-client/src/main/java/io/aeron/AeronCounters.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
Following #1532, this PR introduces snapshot duration tracking to clustered services.
Note that `aeron.cluster.service.snapshot.threshold` property usage sets the threshold value for **all** clustered services. If a per-service threshold setting is needed, `ClusteredServiceContainer.Context#snapshotDurationThresholdNs` API can be used.
> [Java] Introduce clustered service specific SnapshotDurationTracker

- aeron-agent/src/main/java/io/aeron/agent/ChannelEndpointInterceptor.java
- aeron-client/src/main/java/io/aeron/Aeron.java
- aeron-client/src/test/cpp_shared/EmbeddedMediaDriver.h
- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeronmd.h
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-system-tests/src/test/java/io/aeron/ResponseChannelsTest.java
- aeron-system-tests/src/test/java/io/aeron/driver/ExperimentalDriverFeaturesTest.java
- aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
* Add checking for experimental support in the media driver
* Mark response channels as an experimental feature.
> Support configuration flag for experimental features

- aeron-samples/src/main/c/response/response_client.c
- aeron-samples/src/main/c/response/response_server.c
Separate CLI specific code from client/server code to isolate the latter into more of a 'library'
> [C] refactor response client/server code to separate out CLI code

- aeron-client/src/main/cpp/concurrent/AgentRunner.h
[see issue 1592](https://github.com/real-logic/aeron/issues/1592)
> Fix: Set AgentRunner thread name.

- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/c/aeron_network_publication.h
- aeron-driver/src/main/c/aeron_system_counters.c
- aeron-driver/src/main/c/aeron_system_counters.h
- aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
- aeron-driver/src/main/java/io/aeron/driver/ext/FixedLossGenerator.java
- aeron-driver/src/main/java/io/aeron/driver/status/SystemCounterDescriptor.java
- aeron-driver/src/test/java/io/aeron/driver/ext/FixedLossGeneratorTest.java
- aeron-system-tests/src/test/java/io/aeron/DataLossAndRecoverySystemTest.java
Exposes a counter for the number of bytes retransmitted due to resending after receiving NAKs.
Caveats (shown in 44e89dfd7539ea2fa1f6a82655c119ef2681ab97):
- Only counts bytes sent to multiple MDC destinations once
- Retransmitted bytes are not included in total bytes
I looked into addressing those caveats, but I couldn't decide on the best approach.
Would it be best to revert the disabled tests? Whilst it is useful documentation, it will probably rot.
> Expose a "retransmitted bytes" counter

- aeron-client/src/main/c/collections/aeron_int64_counter_map.c
- aeron-client/src/main/c/collections/aeron_int64_counter_map.h
- aeron-client/src/main/c/collections/aeron_int64_to_ptr_hash_map.h
- aeron-client/src/test/c/collections/aeron_int64_counter_map_test.cpp
- aeron-driver/src/main/c/aeron_data_packet_dispatcher.c
- aeron-driver/src/main/c/aeron_data_packet_dispatcher.h
- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/c/aeron_driver_context.c
- aeron-driver/src/main/c/aeron_driver_context.h
- aeron-driver/src/main/c/aeronmd.h
- aeron-driver/src/main/java/io/aeron/driver/Configuration.java
- aeron-driver/src/main/java/io/aeron/driver/DataPacketDispatcher.java
- aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/main/java/io/aeron/driver/PublicationImage.java
- aeron-driver/src/test/c/aeron_data_packet_dispatcher_test.cpp
- aeron-driver/src/test/java/io/aeron/driver/DataPacketDispatcherTest.java
- aeron-driver/src/test/java/io/aeron/driver/ReceiverTest.java
- aeron-system-tests/src/test/java/io/aeron/StreamSessionLimitsTest.java
- aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
Limit the number of sessions that a single stream can have.  By default it is unlimited (specifically 2^31 - 1).  This can help prevent denial of service behaviour by creating too many publications on the same stream.
> Per Stream Session Limits

- aeron-client/src/main/c/util/aeron_fileutil.c
- aeron-client/src/main/c/util/aeron_fileutil.h
- aeron-client/src/test/c/util/aeron_fileutil_test.cpp
- aeron-driver/src/main/c/aeron_driver.c
aeron_mkdir_recursive() will recursively create parent directories until it finds one that's already created.
Also, it calls itself... recursively.
(Windows tests are failing... why is Windows different!?!?!)
> [C] add and use aeron_mkdir_recursive

- aeron-annotations/src/main/java/io/aeron/version/Version.java
- aeron-annotations/src/main/java/io/aeron/version/VersionProcessor.java
This should allow to verify logic of validating versions in a test. 
constants are still there for the cases where access to version info is on the hot path (+ regardless JIT might optimize it anyway?)
> [Java] Version interface to allow testing usage of it

- aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java
get latest valid standby snapshots to replicate expected standby snapshot correctly when consensusModuleAgent starts
> validate standby snapshot

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
Previously, the "take a standby snapshot" control signal could be dropped due to back-pressure when appending to the log.
(Particularly when using small term buffer lengths) this behaviour makes it harder to construct tests where a specific number of standby snapshots are taken. The only option is to wait for the standby snapshot to appear (how long?) and retry if it doesn't, i.e., you can guarantee at least one standby snapshot will be taken but not exactly one. In the Aeron Data Retention Regulator (DRR) tests, where we test the DRR behaviour with a certain number of different kinds of (local vs remote) snapshots, it makes it harder to write reliable tests.
This behaviour also means that from the PremiumClusterTool's perspective, the "take a standby snapshot" signal appears to have been …
> [Java] Process standby snapshot control signals like normal snapshot signals.

- aeron-client/src/main/cpp_wrapper/FragmentAssembler.h
- aeron-client/src/main/cpp_wrapper/Subscription.h
- aeron-client/src/test/cpp_wrapper/PubSubTest.cpp
Josh raised a couple of issues through premium support tickets. More notes in the commit messages. Based on the README, I think it is okay to assume `>= C++11`, but please correct me if I am wrong.
> C++ wrapper improvements

- aeron-archive/src/main/java/io/aeron/archive/AbstractListRecordingsSession.java
- aeron-archive/src/test/java/io/aeron/archive/ListRecordingsForUriSessionTest.java
With the recent reduction to MAX_SCANS_PER_WORK_CYCLE in https://github.com/real-logic/aeron/commit/1c558899c4d8e62b351adac9addd177d9d108f51, we noted that some list operations took significantly longer time, but when profiling it looked like archive was just sleeping.
As it turns out, list recordings only return a positive work count if it actually found something, but this means that a listRecordingsForUri API call that matches only a small subset of recordings (or even none at all) will idle every 64 recordings, which for a large catalog caused the list operation to take multiple seconds of sleeping.
This instead changes work count to be based on the number of recordings processed, which for listRecordings should be exactly the same, but for listRecordingsForUri should only idle if …
> [Java] Reduce archive listRecordingsForUri idling

- aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveToolTests.java
Give the user an option to delete only the orphaned files of the specified recording.
> [Archive]Enhance the ArchiveTool.delete-orphaned-segments method

- cppbuild/cppbuild
When an unknown argument is passed to cppbuild, the exitcode is 0. Making it difficult to determine if the build was a success or a failure (especially if the cppbuild is part of a another script).
This PR changes that by setting the exitcode to 1.
> Unknown cppbuild arg, exit with exitcode=1

- aeron-driver/src/main/c/aeron_ipc_publication.c
- aeron-driver/src/main/c/aeron_publication_image.c
- aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java
- aeron-driver/src/main/java/io/aeron/driver/PublicationImage.java
- aeron-driver/src/test/java/io/aeron/driver/UntetheredSubscriptionTest.java
- aeron-system-tests/src/test/java/io/aeron/UntetheredSubscriptionTest.java
For untethered subscriptions transitioning from resting to active, avoid using their own position in minimum join position
> Tethering join position

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusAdapter.java
Currently the cluster is not able to receive standby snapshot notifications when using an authenticator that checks the credentials.
This is because the provided credentials on standby snapshot notifications are not read.
> Use provided credentials on standby snapshot

- aeron-archive/src/main/cpp/client/AeronArchiveVersion.h
- aeron-client/src/main/cpp/AeronVersion.h
Older libc versions include the file sys/sysmacros.h in sys/types.h which causes name collisions with the major() and minor() functions.
> Undef macros major() and minor() defined in sys/sysmacros.h to prevent name collisions

- aeron-archive/src/main/c/client/aeron_archive_configuration.c
This fixes a duplicate symbol error when linking.
> [C] Remove duplicate definition of aeron_semantic_version_compose.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ServiceIpcIngressMessageTest.java
There is a bug in the Consensus Module where all service messages are appended to the same pending service message queue. The service container sends its service IDs as a session ID whereas the Consensus Module interprets it as a mask. 
Where service messages are being sent from multiple services, these can be enqueued in different orders.
This means during failover/restart pending messages can be skipped or duplicated when a new leader is elected.
This change will affect users who are using cluster.offer() from multiple services.
**Upgrade procedure**
Those affected will need to do a clean shutdown (with a snapshot) and restart the whole cluster with the fix.
Is this upgrade procedure reasonable? How many people who haven't already worked around the duplicate/skipped message behaviour …
> Fix duplicate service messages during failover/restart when using multiple services

- aeron-driver/src/main/java/io/aeron/driver/media/SendChannelEndpoint.java
when the new address is back to the udpChannel.remoteData, this can not be triggered `resolution changes`
> [java]fix resolution bug

- aeron-samples/src/main/java/io/aeron/samples/raw/BurstSendReceiveUdpPing.java
- aeron-samples/src/main/java/io/aeron/samples/raw/ReceiveSendUdpPong.java
- aeron-samples/src/main/java/io/aeron/samples/raw/ReceiveWriteUdpPong.java
- aeron-samples/src/main/java/io/aeron/samples/raw/SelectReceiveSendUdpPong.java
- aeron-samples/src/main/java/io/aeron/samples/raw/SendReceiveUdpPing.java
- aeron-samples/src/main/java/io/aeron/samples/raw/SendSelectReceiveUdpPing.java
- aeron-samples/src/main/java/io/aeron/samples/raw/WriteReceiveUdpPing.java
The ThreadHints class in Agrona has been deprecated and all call to ThreadHints.onSpinWait have been replaced by Thread.onSpinWait.
For more info see:
https://github.com/real-logic/agrona/pull/312
> Replacement of ThreadHints.onSpinWait by Thread.

- aeron-archive/src/main/c/client/aeron_archive_context.c
- aeron-archive/src/main/c/client/aeron_archive_credentials_supplier.c
- aeron-archive/src/main/c/client/aeron_archive_proxy.c
This fixes a segfault when connecting to Archive without the credentials supplier set up.
> [C] Handle connecting to Archive without credentials.

- aeron-client/src/main/cpp_wrapper/concurrent/AgentInvoker.h
- aeron-client/src/main/cpp_wrapper/concurrent/AgentRunner.h
```
/aeron-client/src/main/cpp_wrapper/concurrent/AgentInvoker.h
/aeron-client/src/main/cpp_wrapper/concurrent/AgentRunner.h
```
It seems more appropriate to change the logbuffer::exception_handler_t declared in the constructors of AgentRunner and AgentInvoker to util::exception_handler_t.
> [C++ wrapper] tidy up the namespace for exception_handler_t

- aeron-archive/src/main/c/client/aeron_archive_replay_merge.c
If an error occurs during replay merge, in aeron_async_destination_poll(), async_destination gets freed but never gets set to null.
If aeron_archive_replay_merge_close() is then called to clean up, aeron_archive_replay_merge_handle_async_destination() gets invoked again, which dereferences a dangling replay_merge->async_destination.
> [C] Fix dangling pointer in replay merge.

- aeron-client/src/main/cpp_wrapper/Image.h
- aeron-client/src/main/cpp_wrapper/Publication.h
In the Linux build environment, compiling Publication.h and Image.h results in errors indicating that the required headers for shared_ptr and mutex are missing.
> [C++] Fix the issue with .h file imports in apron-client cpp_wrapper.

- aeron-driver/src/main/c/agent/aeron_driver_agent.c
- aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
`aeron_udp_channel_transport_sendv()` calls `sendmmsg()` under the hood. `sendmmsg()` [manpage](https://manpages.ubuntu.com/manpages/focal/en/man2/send.2freebsd.html) says:
> [EISCONN]          A destination address was specified and the socket is already connected.
We're using `exasock` accellerated TCP stack, which takes it quite literally and returns an error even if specified destination address matches the connected address of the socket. Linux must be more relaxed about it and the old code works fine.
> Fix use of sendmmsg()

- aeron-client/src/main/cpp_wrapper/Subscription.h
Add an AsyncDestination type definition to Subscription.h, similar to how it is done in Publication.h.
If the AsyncDestination type definition is not added to Subscription.h, you will encounter errors when referencing Subscription.h alone
> [C++ Wrapper] Add an AsyncDestination type definition to Subscription.h

- aeron-driver/src/main/c/aeron_ipc_publication.c
- aeron-driver/src/main/c/aeron_network_publication.c
- aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java
- aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
- aeron-driver/src/test/c/aeron_network_publication_test.cpp
- aeron-driver/src/test/java/io/aeron/driver/NetworkPublicationTest.java
This PR ensures that `pub-lmt` always stays within a safe boundary, i.e.:
* either one term ahead of the dirty buffer.
* or two terms ahead of the dirty buffer but only if the clean position offset is non zero, i.e. **not** an entire buffer is dirty.
Explanation: `pub-lmt` is a soft constraint, i.e. it can be breached by a publisher but only within a term boundary. This means that if the publisher fills an entire term and the following term is a dirty one then subscribers (sender or spies) might start reading the dirty data before conductor has a chance to clean it up. Therefore if the clean position is at the term start we don't allow `pub-lmt` to be in the previous term.
> [Java/C] Prevent NetworkPublication's `pub-lmt` from wrapping around into the dirty term.

- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-system-tests/src/test/java/io/aeron/cluster/InitiateShutdownThenImmediatelyCloseLeaderTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/MethodCallBlocker.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
Previously, when issuing a shutdown, via the control toggle, on the leader of a cluster and then immediately closing its ConsensusModule, it was possible that a new leader was elected, and a follower node (in both leadership terms) could send a TerminationAck requested by the first leader to the second leader. As the second leader was not expecting to receive this TerminationAck, it would throw a NPE when attempting to access `ConsensusModuleAgent#clusterTermination`.
For example:
```
java.lang.NullPointerException: Cannot invoke "io.aeron.cluster.ClusterTermination.canTerminate(io.aeron.cluster.ClusterMember[], long)" because "this.clusterTermination" is null
at io.aeron.cluster.ConsensusModuleAgent.onTerminationAck(ConsensusModuleAgent.java:1201)
at …
```
> Only send TerminationAck to the leader that requested it.

- aeron-archive/src/main/java/io/aeron/archive/Archive.java
- aeron-archive/src/main/java/io/aeron/archive/ArchiveMarkFile.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveContextTest.java
- aeron-archive/src/test/java/io/aeron/archive/ArchiveMarkFileTest.java
- aeron-client/src/main/c/aeron_cnc.c
- aeron-client/src/main/c/aeron_cnc_file_descriptor.h
- aeron-client/src/main/c/aeronc.h
- aeron-client/src/main/java/io/aeron/Aeron.java
- aeron-client/src/main/java/io/aeron/CncFileDescriptor.java
- aeron-client/src/main/java/io/aeron/CommonContext.java
- aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java
- aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java
- aeron-cluster/src/test/java/io/aeron/cluster/ClusterBackupContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleContextTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ClusterMarkFileTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/service/ClusteredServiceContainerContextTest.java
- aeron-driver/src/main/c/aeron_driver.c
- aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
- aeron-driver/src/test/java/io/aeron/driver/MediaDriverContextTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterBackupContextTest.java
- aeron-system-tests/src/test/java/io/aeron/driver/FilePageSizeTest.java
- aeron-system-tests/src/test/java/io/aeron/driver/SystemCountersTest.java
- aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
This PR implement mark file length alignment based on the `aeron.file.page.size` configured on the media driver. The file page size value is now stored in the CnC file.
> File page aligned mark files.

- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
- aeron-cluster/src/test/java/io/aeron/cluster/client/AeronClusterTest.java
Currently, AeronCluster does very little to track its connection status. All applications that want to react to, for example, losing network connectivity to the leader or the cluster shutting down, need to implement custom logic. This change provides such logic out of the box.
If connection is lost for more than newLeaderTimeoutNs, or a message can't be sent to a new leader for newLeaderConnectionTimeoutNs, the client will close itself.
For applications which call pollEgress/controlledPollEgress and check isClosed afterward no changes are needed. For applications which use the ingress publication or the egress subscription directly, two methods were added: trackIngressPublicationResult and pollStateChanges.
For the new leader timeout we currently use twice the default leader heartbeat …
> [Java] Make AeronCluster track connection status.

- aeron-cluster/src/main/java/io/aeron/cluster/ClusterSession.java
- aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
- aeron-cluster/src/main/java/io/aeron/cluster/IngressAdapter.java
- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
- aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
- aeron-cluster/src/test/java/io/aeron/cluster/ConsensusModuleAgentTest.java
- aeron-cluster/src/test/java/io/aeron/cluster/IngressAdapterTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterSessionReliabilityTest.java
- aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
- aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
- aeron-test-support/src/main/java/io/aeron/test/driver/PortLossGenerator.java
- aeron-test-support/src/main/java/io/aeron/test/driver/StreamIdLossGenerator.java
It's possible that after some transient network issue where an image goes unavailable and then available again, a leader will process ingress messages with a gap, and similarly it's possible that a client will process egress messages with a gap. This silent message loss could lead to issues in application protocols which do not expect gaps, so we want to prevent that. This should be very unlikely with the default settings though.
The commits:
- fix the issue on the cluster side for ingress,
- add an optimization to close a session when image goes unavailable without waiting for the session timeout,
- fix the issue on the client side for egress.
A breaking change if someone would run an old client and a new one on the same driver with the same channel, because different rejoin settings are …
> Prevent message gaps in cluster sessions

- aeron-driver/src/main/c/media/aeron_udp_destination_tracker.c
- aeron-system-tests/src/test/java/io/aeron/SpySimulatedConnectionTest.java
The Java media driver sets the initial result ('bytes sent' effectively) to the number of bytes to be sent in the two implementations of `MultiSndDestination#send()`.  The first commit here does the same for the equivalent function in the C media driver.  The second commit is a new system test that fails when run against the C media driver before the fix.
> MDC short send fix

- aeron-samples/src/main/java/io/aeron/samples/archive/IndexedReplicatedRecording.java
When running this IndexedReplicatedRecording example, the following error will be reported.
It seems to be an issue with the LIVE_CHANNEL configuration, I've submitted this MR to fix it. Please review it.
```
Exception in thread "main" io.aeron.exceptions.RegistrationException: ERROR - java.lang.IllegalArgumentException : 'control' parameter requires that either 'endpoint' or 'control-mode' is specified, channel=aeron:udp?control=localhost:8100|term-length=65536, errorCodeValue=11
at io.aeron.ClientConductor.onError(ClientConductor.java:224)
at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:116)
at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:69)
at …
```
> [Java] Fix IndexedReplicatedRecording LIVE_CHANNEL config

- aeron-driver/src/main/c/aeron_driver_conductor.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
- aeron-driver/src/main/c/media/aeron_send_channel_endpoint.h
- Removes the managed resource lifecycle between removing the endpoint from the sender and closing the underlying socket.
- If an send channel endpoint is found in the closing state, respond with a temporary resource error.
- Reduces the window of time where we can end up with a port bind error to a very small amount.
> [C] More immediate close of send channel endpoints

- aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
When member changes or ingressChannel only config follower endpoints, the memberByIdMap only contains follower endpoints. During the AeronCluster connection process, the follower will return a redirection request containing information about all the nodes in the cluster. All Publications will be closed, including the ingressPublication.
In the current implementation, if the ingressChannel does not contain the Leader information, it cannot correctly handle the redirect request, even though the egressPoller already includes information about all the nodes in the cluster.
If, in the UpdateMember function, we check whether ingressPublication is closed or set ingressPublication to null, this situation can be handled correctly.
> Ensures proper handling when ingress publication is closed but not null
