aeron-io/aeron

aeron-common/src/main/cpp/CMakeLists.txt
aeron-common/src/main/cpp/concurrent/Atomic64.h
aeron-common/src/main/cpp/concurrent/AtomicBuffer.h
aeron-common/src/main/cpp/concurrent/AtomicCounter.h

original pull request #54 from @phaynes with conflicts removed and added copyright.

merging @phaynes changes from #54

---

aeron-common/src/main/java/uk/co/real_logic/aeron/common/CommonContext.java
aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/MediaDriver.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/BasicPublisher.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/BasicSubscriber.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/EmbeddedPingPong.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/EmbeddedThroughput.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/Ping.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/Pong.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/RateSubscriber.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/StreamingPublisher.java

Implemented 3 improvements as described in issue #90 and updated samples to demonstrate usage.

Pull request with proposed embedded media driver usability improvements

---

aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/DriverPublication.java

This issue was causing invalid retransmits.
I believe this fixes #93.

Fix calculation of bytes sent.

---

aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/raw/Common.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/raw/ReceiveWriteUdpPong.java
aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/raw/WriteReceiveUdpPing.java

NIO performance test using write instead of send on a DatagramChannel

[Java] benchmark of writing to a DatagramChannel

---

aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/LossDetector.java

During multiple merge steps, this code got lost. Adding it again.

Adding missing code which got lost during merge

---

aeron-tools/src/main/java/uk/co/real_logic/aeron/tools/SubscriberTool.java

Needed to make a wrapper class for each subscription so I can associate a FragmentHandler to a specific Subsciption. The new poll() API seems clunky for this common use case.

Modified SubscriberTool to pass FragmentHandler to poll method

---

aeron-samples/src/main/java/uk/co/real_logic/aeron/samples/AeronStat.java

Hi,
I made an attempt at resolving this enhancement https://github.com/real-logic/Aeron/issues/167.
Please review and let me know of any changes required.
Thanks,

converting AeronStat into a util class that can be used to print data to a stream

---

aeron-samples/scripts/aeron-stat.bat
aeron-samples/scripts/basic-publisher.bat
aeron-samples/scripts/basic-subscriber.bat
aeron-samples/scripts/error-stat.bat
aeron-samples/scripts/logging-media-driver.bat
aeron-samples/scripts/low-latency-media-driver.bat
aeron-samples/scripts/media-driver.bat
aeron-samples/scripts/ping.bat
aeron-samples/scripts/pong.bat
aeron-samples/scripts/rate-subscriber.bat
aeron-samples/scripts/streaming-publisher.bat

Adjust paths
Handle space in JAVA_HOME (c:\Program Files\java..)

[Java] Allow windows sample files to be launched by double-clicking

---

aeron-client/src/main/cpp/util/BitUtil.h

The __lzcnt instruction is not returning the correct value. (Apparently, when compiling with VS it only works on newer CPUs.) I modified the find next power of 2 function so that it doesn't rely on this function. I also removed the count leading zeros function, since it will generate incorrect information on some CPUs. (Although, it could be left in or modified.) With this change all the C++ tests are passing on Windows.

Made finding the next power of 2 more portable.

---

aeron-agent/src/test/java/io/aeron/agent/EventConfigurationTest.java
aeron-driver/src/main/java/io/aeron/driver/Configuration.java
aeron-driver/src/main/resources/aeron-ipc.properties
aeron-driver/src/main/resources/aeron-throughput.properties
aeron-driver/src/main/resources/low-latency.properties

This should fix half of #331. Namely, it allows you to specify byte based sizes with suffixes of k, m, or g.
I'll put together a pr for the other half (time units) if or once you're happy with this. Any other tests or anything you reckon this needs?

[Java]: Add magnitudes to property files

---

aeron-agent/src/test/java/io/aeron/agent/EventConfigurationTest.java
aeron-driver/src/main/java/io/aeron/driver/Configuration.java

This is the other half of #331.

[Java] parse times from properties with suffixes of ns, us, ms or s.

---

aeron-client/src/main/java/io/aeron/ExclusivePublication.java
aeron-client/src/main/java/io/aeron/Publication.java

This should close #404.
Not sure if this is the approach you had in mind or not. (Figure you might have meant having an abstract class or duplicating the logic or something else?) Let me know if this fits with what you want, I'm totally happy to rework it if you had something else in mind.

[Java] have ExclusivePublication extend Publication.

---

CMakeLists.txt
cppbuild/cppbuild-vs.cmd

This adds support for enabling warnings as errors, and building the driver to the microsoft build command

[C++] Windows build command mirroring linux/osx

---

aeron-client/src/main/java/io/aeron/Aeron.java
aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java
aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java

- Fix missed AeronDirectory override
- Show full path when failing to connect to driver
- Fix ClusterTool command to match usage

Various Minor Fixes

---

aeron-client/src/main/java/io/aeron/logbuffer/TermAppender.java
aeron-client/src/test/java/io/aeron/logbuffer/TermAppenderTest.java

`vectorOffset` could do with a more descriptive name... any suggestions?

Fix bug in TermAppender

---

aeron-cluster/src/main/java/io/aeron/cluster/SequencerAgent.java
aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java
aeron-cluster/src/main/java/io/aeron/cluster/service/RecordingLog.java

Reverts real-logic/aeron#478 due to broken build.

Revert "Recovery from snapshot"

---

aeron-driver/src/main/java/io/aeron/driver/media/SocketAddressUtil.java
aeron-driver/src/test/java/io/aeron/driver/media/SocketAddressUtilTest.java

Replace regex with state machine based parser, #486.

[Java] Remove regular expressions from socket address parsing.

---

aeron-client/src/main/cpp/Subscription.h
aeron-client/src/main/java/io/aeron/Subscription.java

Revert "Change the round-robin mechanism of Subscription's poll methods"

---

aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
aeron-cluster/src/test/java/io/aeron/cluster/ClusterFollowerTest.java

Close commitPosition to avoid multiple counters after an election:
```
81:                3,968 - rec-pos: 0 -1324327184 100 aeron:udp?control=192.168.222.12:10007|sparse=true|session-id=-1324327184
82:                3,968 - commit-pos: leadershipTermId=1
83:                   34 - Sequence Number
84:               99,999 - Current Value
85:                1,408 - commit-pos: leadershipTermId=0
86:                    0 - pub-pos (sample): 110 -1324327176 102 aeron:udp?endpoint=192.168.222.10:10000
```

Multiple commit position counters

---

aeron-system-tests/src/test/java/io/aeron/SessionSpecificSubscriptionTest.java

Hi! Thank you very much for this test it makes so much sense for me and helps to understand how sessionId works. 
But i think with this patch makes the test a little bit more useful for people like me who tries to figure out what sessionId is.
but feel free to decline it if you think it's redurant.

Improve SessionSpecificSubscriptionTest with new case shouldNotSubscribeWithoutSpecificSession

---

aeron-client/src/main/cpp/Image.h
aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
aeron-client/src/main/cpp/concurrent/logbuffer/Header.h
aeron-client/src/main/cpp/concurrent/logbuffer/LogBufferDescriptor.h

Add assertions and cleanup

---

aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java
aeron-cluster/src/test/java/io/aeron/cluster/RecordingLogTest.java

Adds a unit test, requiring that a static method on `RecordingLog` was given package-protected access. If you prefer, I could pull the sorting logic out to another utility class so that `RecordingLog.addSnapshots` can have `private` access.

[Java] Fix indexing bug when adding snapshots to RecoveryPlan

---

aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java

Fails with:
```
io.aeron.cluster.client.ClusterException: invalid service ACK: serviceId=0, logPosition=192 expected 1280, ackId=4 expected 4
at io.aeron.cluster.ConsensusModuleAgent.validateServiceAck(ConsensusModuleAgent.java:2097)
at io.aeron.cluster.ConsensusModuleAgent.onServiceAck(ConsensusModuleAgent.java:776)
at io.aeron.cluster.ConsensusModuleAdapter.onFragment(ConsensusModuleAdapter.java:100)
at io.aeron.logbuffer.TermReader.read(TermReader.java:75)
at io.aeron.Image.poll(Image.java:290)
at io.aeron.Subscription.poll(Subscription.java:206)
at io.aeron.cluster.ConsensusModuleAdapter.poll(ConsensusModuleAdapter.java:51)
at io.aeron.cluster.ConsensusModuleAgent.consensusWork(ConsensusModuleAgent.java:1647)
at io.aeron.cluster.ConsensusModuleAgent.doWork(ConsensusModuleAgent.java:279 …
```

[Java] Add cluster tests.

---

aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java

Where term buffer length > the archive's configured segment length.

Fix segment length in Catalog 

---

aeron-driver/src/main/c/concurrent/aeron_spsc_rb.c
aeron-driver/src/main/c/concurrent/aeron_spsc_rb.h

If this is not the correct approach I can create a scoped aeron_spsc_iovec (comments @tmontgomery ?).

Use system defined iovec rather than a custom one.

---

.travis.yml

Configure build scans to be triggered when running on CI

Trigger scans when run on CI

---

aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
aeron-cluster/src/test/java/io/aeron/cluster/ClusterNodeTest.java

Adds a delegating `tryClaim` method to `AeronCluster` that adds the cluster ingress header to the claimed buffer region.

Add tryClaim method to AeronCluster

---

aeron-archive/src/main/java/io/aeron/archive/Catalog.java
aeron-archive/src/main/java/io/aeron/archive/CatalogTool.java
aeron-archive/src/main/java/io/aeron/archive/CatalogView.java
aeron-archive/src/test/java/io/aeron/archive/CatalogTest.java
aeron-archive/src/test/java/io/aeron/archive/CatalogViewTest.java

Only open the Catalog in read write mode when required. This allows reading the catalog when a user only has read permission.

[Java] Readonly view of the Catalog.

---

aeron-client/src/main/java/io/aeron/ClientConductor.java

Hopefully a useful data-point if these exceptions do occur.

Add observed values to timeout messages

---

aeron-client/src/main/cpp/Aeron.h
aeron-client/src/main/cpp/ClientConductor.h
aeron-client/src/main/cpp/Subscription.cpp
aeron-client/src/main/cpp/Subscription.h
aeron-client/src/main/cpp/concurrent/AtomicBuffer.h
aeron-client/src/main/cpp/concurrent/BackOffIdleStrategy.h

Fixes a few warnings and static analyzer issues.

C++ small issues

---

aeron-system-tests/src/test/java/io/aeron/SessionSpecificSubscriptionTest.java

Mostly useful as documentation...

Test showing some of the explicit session id failure cases.

---

aeron-system-tests/src/test/java/io/aeron/SessionSpecificPublicationTest.java

Showing test for both UDP and IPC media.

[Java] Parameterise SessionSpecificSubscriptionTest

---

aeron-client/src/main/cpp/Image.h

Easier to review with No Whitespace set in the diff view.

[C++] Invert logic and return early in Image methods.

---

aeron-agent/src/main/java/io/aeron/agent/EventLogAgent.java
aeron-agent/src/test/java/io/aeron/agent/ArchiveLoggingAgentTest.java

Fixed archive instrumentation in `aeron-agent` and added a test for it.

[Java] Fix archive instrumentation.

---

aeron-client/src/main/cpp/Image.h
aeron-client/src/test/cpp/ImageTest.cpp

This is mostly a copy of `boundedControlledPoll` without the overhead of
the control checks at each iteration.

[C++] Add Image::boundedPoll().

---

aeron-driver/src/main/c/uri/aeron_uri.c
aeron-driver/src/test/c/aeron_uri_test.cpp

Also includes some formatting clean ups and refactoring the parsing to use a common int32_t parsing function.

Test and Fix for undefined behaviour when parsing term-id/initial-term-id

---

aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
aeron-driver/src/test/java/io/aeron/driver/MediaDriverContextTest.java

Fix `nakMulticastMaxBackoffNs()` and add a test.

[Java] Fix `nakMulticastMaxBackoffNs()` to assign provided value

---

aeron-driver/src/main/c/CMakeLists.txt
aeron-driver/src/main/c/aeron_socket.c
aeron-driver/src/main/c/aeron_socket.h
aeron-driver/src/main/c/media/aeron_udp_transport_poller.c
aeron-driver/src/main/c/media/aeron_udp_transport_poller.h

Relate to #779 
Use `WSAPoll` for polling on windows

[C] Add WSAPoll for windows support

---

build.gradle
config/checkstyle/checkstyle.xml

Migrated `checkstyle.xml` using the following migration notes: https://github.com/checkstyle/checkstyle/issues/7329

[Java] Upgrade to Checkstyle 8.28

---

aeron-cluster/src/test/java/io/aeron/cluster/BackupTest.java
aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java
aeron-cluster/src/test/java/io/aeron/cluster/DynamicMembershipTest.java
aeron-cluster/src/test/java/io/aeron/cluster/StartFromTruncatedRecordingLogTest.java
aeron-system-tests/src/test/java/io/aeron/PongTest.java
aeron-test-support/src/main/java/io/aeron/test/SlowTest.java
build.gradle
settings.gradle

Went with an aeron-test-support module for now, to save lots of back and forth with gradle and maven central.  We can pull up to agrona anything that may be valuable for SBE as that happens.

Add aeron-test-support module and @SlowTest annotation.

---

aeron-agent/src/main/java/io/aeron/agent/CommonEventDissector.java
aeron-agent/src/main/java/io/aeron/agent/EventLogReaderAgent.java
aeron-agent/src/test/java/io/aeron/agent/CommonEventDissectorTest.java
aeron-agent/src/test/java/io/aeron/agent/DriverLoggingAgentTest.java
aeron-system-tests/src/test/java/io/aeron/BufferClaimMessageTest.java
aeron-system-tests/src/test/java/io/aeron/ExclusivePublicationTest.java
aeron-system-tests/src/test/java/io/aeron/FragmentedMessageTest.java
aeron-system-tests/src/test/java/io/aeron/GapFillLossTest.java
aeron-system-tests/src/test/java/io/aeron/ImageAvailabilityTest.java
aeron-system-tests/src/test/java/io/aeron/MemoryOrderingTest.java
aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
aeron-system-tests/src/test/java/io/aeron/MultiDestinationSubscriptionTest.java
aeron-system-tests/src/test/java/io/aeron/MultiSubscriberTest.java
aeron-system-tests/src/test/java/io/aeron/PongTest.java
aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java
aeron-system-tests/src/test/java/io/aeron/PublicationUnblockTest.java
aeron-system-tests/src/test/java/io/aeron/PublishFromArbitraryPositionTest.java
aeron-system-tests/src/test/java/io/aeron/SessionSpecificPublicationTest.java
aeron-system-tests/src/test/java/io/aeron/SessionSpecificSubscriptionTest.java
aeron-system-tests/src/test/java/io/aeron/SpySimulatedConnectionTest.java
aeron-system-tests/src/test/java/io/aeron/SpySubscriptionTest.java
aeron-system-tests/src/test/java/io/aeron/StopStartSecondSubscriberTest.java
aeron-system-tests/src/test/java/io/aeron/TermBufferLengthTest.java
aeron-system-tests/src/test/java/io/aeron/UntetheredSubscriptionTest.java
aeron-system-tests/src/test/java/io/aeron/archive/ArchiveTest.java

- Timezone based failure in NZ.
- Use less ephemeral ports.

Unit test fixes.

---

.github/workflows/ci-low-cadence.yml
.github/workflows/ci.yml

Runs in about 7 minutes in CI.  Runs any test tagged with @SlowTest.

[Java] Add slow test Github actions target (linux, jdk11 only).

---

aeron-driver/src/main/c/media/aeron_udp_channel_transport.c

Currently it uses file close which causes hard crash

Use socket close on Windows

---

aeron-driver/src/main/c/concurrent/aeron_thread.c

[C] SetWaitableTimer expects a duration in 100-nanosecond intervals

---

aeron-driver/src/main/java/io/aeron/driver/AbstractMinMulticastFlowControl.java
aeron-driver/src/main/java/io/aeron/driver/FlowControlParameterParser.java
aeron-driver/src/main/java/io/aeron/driver/MinMulticastFlowControl.java
aeron-driver/src/main/java/io/aeron/driver/TaggedMulticastFlowControl.java

- Adds abstract base class `AbstractMinMulticastFlowControl`.
- Adds Tagged and Min strategies as subclasses of the abstract superclass.
- Separates out flow control parsing.

[Java] Consolidate tagged and min flow control strategies.

---

aeron-driver/src/main/c/aeron_driver_context.c
aeron-driver/src/main/c/aeron_driver_context.h
aeron-driver/src/main/c/aeron_flow_control.c
aeron-driver/src/main/c/aeron_flow_control.h
aeron-driver/src/main/c/aeron_min_flow_control.c
aeron-driver/src/main/c/aeronmd.h
aeron-driver/src/test/c/aeron_flow_control_test.cpp

For parity with the Java media driver.

[C] Consolidate min and tagged flow control in the C media driver.

---

aeron-client/src/main/java/io/aeron/CommonContext.java
aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
aeron-driver/src/main/java/io/aeron/driver/media/SocketAddressParser.java
aeron-driver/src/main/java/io/aeron/driver/media/UdpChannel.java
aeron-driver/src/main/java/io/aeron/driver/media/UdpNameResolutionTransport.java
aeron-driver/src/main/java/io/aeron/driver/reports/ErrorReportUtil.java
aeron-driver/src/test/java/io/aeron/driver/media/SocketAddressParserTest.java
aeron-samples/src/main/java/io/aeron/samples/ErrorStat.java
aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
aeron-system-tests/src/test/java/io/aeron/NameReResolutionTest.java
aeron-system-tests/src/test/java/io/aeron/test/CTestMediaDriver.java
aeron-system-tests/src/test/java/io/aeron/test/DistinctErrorLogTestWatcher.java
aeron-system-tests/src/test/java/io/aeron/test/ErrorReportTestUtil.java
aeron-system-tests/src/test/java/io/aeron/test/MediaDriverTestWatcher.java
aeron-system-tests/src/test/java/io/aeron/test/StubCsvNameResolver.java
aeron-system-tests/src/test/java/io/aeron/test/TestMediaDriver.java
aeron-test-support/src/main/java/io/aeron/test/Counters.java
aeron-test-support/src/main/java/io/aeron/test/CountingFragmentHandler.java
aeron-test-support/src/main/java/io/aeron/test/Tests.java

System test updates for the C media driver implementation of name re-resolution

---

aeron-cluster/src/test/java/io/aeron/cluster/ClusterTest.java

Leaves two nodes in a LEADER_TRANSITION state and the cluster does not recover.
Warnings:
```
Warning in node 1 io.aeron.cluster.client.ClusterException : leader heartbeat timeout
Warning in node 0 io.aeron.cluster.client.ClusterException : leader heartbeat timeout
Warning in node 0 io.aeron.cluster.client.ClusterException : unexpected vote request
Warning in node 0 io.aeron.cluster.client.ClusterException : no catchup progress
```
Consensus module stuck in:
```
"consensus-module" #17 prio=5 os_prio=0 tid=0x000000001f950000 nid=0x4070 waiting on condition [0x000000002333e000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
at …
```

[Java] Add test for kill the leader twice and attempting to recover.

---

aeron-driver/src/main/c/aeron_driver_conductor.c
aeron-driver/src/main/c/aeron_driver_conductor.h
aeron-driver/src/test/c/aeron_driver_conductor_counter_test.cpp
aeron-driver/src/test/c/aeron_driver_conductor_ipc_test.cpp
aeron-driver/src/test/c/aeron_driver_conductor_network_test.cpp
aeron-driver/src/test/c/aeron_driver_conductor_spy_test.cpp
aeron-driver/src/test/c/aeron_driver_conductor_test.h
aeron-system-tests/src/test/java/io/aeron/LifecycleTest.java

In the C media driver.
- I'm still in the process of reviewing the tests.  I've modified them sufficiently to get them to pass and not have a terrible merge with some of the other code that is coming.  I'm working on some slightly different patterns to make the tests less rigid.

Support Available/Unavailable notifications for client heartbeat counters

---

aeron-cluster/src/test/java/io/aeron/cluster/ClusterBackupTest.java

Test currently fails with:
```
*** Error in node 3 followed by system thread dump ***
io.aeron.cluster.client.ClusterException: leadershipTermId out of sequence: previous 1 this 0
at io.aeron.cluster.RecordingLog.appendSnapshot(RecordingLog.java:839)
at io.aeron.cluster.ClusterBackupAgent.updateRecordingLog(ClusterBackupAgent.java:734)
at io.aeron.cluster.ClusterBackupAgent.doWork(ClusterBackupAgent.java:194)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
at java.lang.Thread.run(Thread.java:748)
```
Steps:
1. Start Cluster
1. Clean Shutdown (with snapshot)
1. Start Cluster
1. Start ClusterBackup
It seems the log entry for term 1 is being added to the recording.log before the snapshot entry for the …

[Java] Add ClusterBackup test around cluster clean shutdown.

---

aeron-client/src/main/c/aeron_context.c
aeron-client/src/main/c/aeronc.h

Couldn't find any other instances of this typo in the code.

[C]: Minor typo fix

---

.github/workflows/release.yml
aeron-cluster/src/main/java/io/aeron/cluster/service/ClientSession.java
aeron-samples/scripts/cluster/basic-auction-client
aeron-samples/scripts/cluster/basic-auction-cluster
aeron-samples/scripts/cluster/script-common
aeron-samples/src/docs/asciidoc/Cluster-Tutorial.asciidoc
aeron-samples/src/docs/asciidoc/ClusterTutorial.adoc
aeron-samples/src/main/java/io/aeron/samples/tutorial/cluster/BasicAuctionClusterClient.java
aeron-samples/src/main/java/io/aeron/samples/tutorial/cluster/BasicAuctionClusteredService.java
aeron-samples/src/main/java/io/aeron/samples/tutorial/cluster/BasicAuctionClusteredServiceNode.java
build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/io/aeron/build/AsciidocUtil.java
buildSrc/src/main/java/io/aeron/build/AsciidoctorPreprocessTask.java
buildSrc/src/main/java/io/aeron/build/GithubUtil.java
buildSrc/src/main/java/io/aeron/build/TutorialPublishTask.java

Includes:
- Asciidoc cluster tutorial
- Sample code
- Calls to gradle asciidoctor plugin to render during the build.

Cluster tutorial

---

aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java

Revert "Add backoff period after exception in ClusterBackupAgent"

---

aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java

Avoids race where the snapshot finishes being replicated before Cluster Backup sees it.

Use recording signals to monitor snapshot progress in Cluster Backup

---

aeron-client/src/main/cpp/ExclusivePublication.h

Removed non const version of channelStatus() from ExclusivePublication

---

aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java

- Fix case where snapshot is first entry in recording.log (which can happen if log leadership term id > snapshot leadership term id)
- Close recording when resetting

Minor ClusterBackup changes

---

aeron-client/src/main/c/aeron_context.c
aeron-client/src/main/c/aeronc.h
aeron-client/src/main/c/util/aeron_parse_util.c
aeron-client/src/main/c/util/aeron_parse_util.h
aeron-driver/src/main/c/aeron_driver_context.c

Also moves parse_boolean into the client's aeron_parse_util.

[C] Allow configuration of pre-touch mapped memory in the c client.

---

aeron-driver/src/main/c/aeron_driver.c

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

[C] UDP retrieve default_rcvbuf properly.

---

aeron-client/src/main/c/aeron_windows.c
aeron-client/src/main/c/aeron_windows.h
aeron-client/src/main/c/util/aeron_clock.c
aeron-client/src/main/c/util/aeron_clock.h

int aeron_clock_gettime_monotonic(struct timespec *tp);
int aeron_clock_gettime_realtime(struct timespec *tp);
Convert aeron_agent_epoch_clock to aeron_epoch_clock

Use the shared aeron_clock_gettime_monotonic, aeron_clock_gettime_realtime and aeron_epoch_clock

---

aeron-client/src/main/c/aeron_context.c
aeron-client/src/main/c/aeron_socket.c
aeron-client/src/main/c/aeron_socket.h
aeron-client/src/main/c/util/aeron_arrayutil.h
aeron-client/src/main/c/util/aeron_dlopen.c
aeron-client/src/main/c/util/aeron_dlopen.h
aeron-client/src/main/c/util/aeron_fileutil.c
aeron-client/src/main/c/util/aeron_fileutil.h
aeron-driver/src/main/c/aeron_driver.c
aeron-driver/src/main/c/aeron_driver_context.c
aeron-driver/src/main/c/media/aeron_udp_channel_transport.c
aeron-driver/src/main/c/media/aeron_udp_transport_poller.c

There is no need guard these code with AERON_CPU_X64

Remove usage AERON_CPU_X64 as much as possible.

---

.github/workflows/ci.yml
aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
aeron-driver/src/main/java/io/aeron/driver/DriverNameResolver.java
aeron-samples/scripts/cluster/agent-ns
aeron-samples/scripts/cluster/remove-namespaces
aeron-samples/scripts/cluster/setup-namespaces
aeron-samples/src/main/java/io/aeron/samples/cluster/EchoServiceNode.java
aeron-system-tests/src/test/java/io/aeron/cluster/ClusterNetworkTopologyTest.java
aeron-test-support/src/main/java/io/aeron/test/launcher/FileResolveUtil.java
aeron-test-support/src/main/java/io/aeron/test/launcher/RemoteLaunchClient.java
build.gradle

- Construct a virtual network that has 2 network buses.
- Add parameters to topology test that puts cluster traffic on a separate bus to ingress.
- Add CI build target for topology tests.

Multi bus topology test

---

.github/workflows/ci-low-cadence.yml
aeron-cluster/src/main/java/io/aeron/cluster/Election.java
aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java

Ensure that `CANDIDATE_BALLOT -> FOLLOWER_LOG_REPLAY` transition leaves node in the `FOLLOWER` role.

Fix bug where followers list does not contain the expected entries.

---

aeron-driver/src/main/c/aeron_driver_conductor.c
aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c
aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.h
aeron-driver/src/main/c/media/aeron_receive_destination.c
aeron-driver/src/main/c/media/aeron_receive_destination.h
aeron-driver/src/test/c/aeron_publication_image_test.cpp
aeron-driver/src/test/c/aeron_receiver_test.h

So that the udp_channel of both the enclosing multi-destination channel and destination are provided.  For simple channels the same value is provided for both parameters.

[C] Restructure the setup of destination construction.

---

aeron-cluster/src/main/java/io/aeron/cluster/PriorityHeapTimerService.java

So that it can be used as a supplier in the consensus module configuration.

Make PriorityHeapTimerService public

---

aeron-cluster/src/main/java/io/aeron/cluster/PriorityHeapTimerService.java
aeron-cluster/src/test/java/io/aeron/cluster/PriorityHeapTimerServiceTest.java

Sometimes need to shift up instead of down to maintain heap invariant.

[Java] Fixed bug in PriorityHeapTimerService.cancelTimerByCorrelationId.

---

aeron-archive/src/main/java/io/aeron/archive/ArchiveConductor.java
aeron-archive/src/main/java/io/aeron/archive/ReplaySession.java

Very helpful to understand why a detach/purgeSegments failed.

[Java] Add more details about current replay session which causes archive detach to fail.

---

aeron-agent/src/main/java/io/aeron/agent/ClusterEventDissector.java
aeron-agent/src/main/java/io/aeron/agent/ClusterEventEncoder.java
aeron-agent/src/main/java/io/aeron/agent/ClusterEventLogger.java
aeron-agent/src/main/java/io/aeron/agent/ClusterInterceptor.java
aeron-agent/src/main/java/io/aeron/agent/CommonEventDissector.java
aeron-agent/src/test/java/io/aeron/agent/ClusterEventLoggerTest.java
aeron-cluster/src/main/java/io/aeron/cluster/ConsensusAdapter.java
aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
aeron-cluster/src/main/java/io/aeron/cluster/ConsensusPublisher.java
aeron-cluster/src/main/java/io/aeron/cluster/Election.java
aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java

Set flag if appendPosition occurs during catchup.  Resend stopCatchup if catchup flag set on appendPosition even if replay has already been stopped.

[Java] Add flags to appendPosition message. 

---

aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleAgent.java
aeron-cluster/src/main/java/io/aeron/cluster/Election.java
aeron-cluster/src/test/java/io/aeron/cluster/ElectionTest.java

- Remove `replayLeadershipTermId` field.
- Set `timeOfLastAppendPositionUpdateNs` when `lastAppendPosition` changes.

[Java] Consensus module touchups.

---

aeron-client/src/main/java/io/aeron/Publication.java
aeron-client/src/test/java/io/aeron/PublicationTest.java

Convenience method to get a readable error message from a position value returned from `offer`.

Publication Error String

---

aeron-system-tests/src/test/java/io/aeron/MinFlowControlSystemTest.java
aeron-system-tests/src/test/java/io/aeron/MultiDestinationCastTest.java
aeron-system-tests/src/test/java/io/aeron/TaggedFlowControlSystemTest.java
aeron-system-tests/src/test/java/io/aeron/TimestampingSystemTest.java
aeron-system-tests/src/test/java/io/aeron/archive/ArchiveTest.java
aeron-system-tests/src/test/java/io/aeron/cluster/ClusterBackupTest.java
aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
aeron-system-tests/src/test/java/io/aeron/cluster/DynamicMembershipTest.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestBackupNode.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java
aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
aeron-test-support/src/main/java/io/aeron/test/driver/DriverOutputConsumer.java
aeron-test-support/src/main/java/io/aeron/test/driver/TestMediaDriver.java
build.gradle

Adds small changes to make it possible to test ATS with the Java system tests.
- Pass through system properties to configure the driver correctly
- Ignore specific errors

ATS System Tests

---

aeron-samples/src/main/c/CMakeLists.txt
aeron-samples/src/main/c/basic_mds_subscriber.c
aeron-samples/src/main/c/basic_publisher.c

- Send a full MTU sized message via basic_publisher
- Adds basic_mds_subscriber

Sample large message

---

aeron-archive/src/main/java/io/aeron/archive/ReplaySession.java

[Java] Improve clarity of error messages on Archive ReplaySession

---

aeron-client/src/main/c/concurrent/aeron_mpsc_rb.c
aeron-client/src/main/c/concurrent/aeron_mpsc_rb.h
aeron-client/src/main/c/concurrent/aeron_spsc_rb.c
aeron-client/src/main/c/concurrent/aeron_spsc_rb.h
aeron-client/src/test/c/concurrent/aeron_mpsc_rb_test.cpp
aeron-client/src/test/c/concurrent/aeron_spsc_rb_test.cpp
aeron-driver/src/main/c/aeron_driver_conductor.c
aeron-driver/src/main/c/aeron_driver_conductor.h
aeron-driver/src/main/c/aeron_driver_context.h

- Reduce the possibility of deadlocking with too many client commands.

Backpressure client commands in the C driver

---

aeron-cluster/src/main/java/io/aeron/cluster/ClusterTool.java

Adds an `is-leader` command to the Cluster Tool. This returns zero if the cluster node is the leader and non-zero if not.

[Java] Cluster tool is leader

---

aeron-archive/src/test/java/io/aeron/archive/ArchiveTest.java

This commit adds a (disabled) test that reproduces an issue we saw in a testing environment where a replay fails.
We observed this in Aeron `1.40.0`, but I believe it is still present (as of cab4a6d83dcf62f832d3c9f8e343a3ba44ad8dd6).
Overview of the issue:
- A message of `maxMessageLength` (or close to it) is offered
- It "fits" into the current term before fragmentation: `termOffset + maxMessageLength < termLength`
- but the message does not fit after fragmentation: `termOffset + requiredLength > termLength`
- ExclusivePublication writes padding where `paddingLength > maxMessageLength`
- ReplaySession fails to recreate due to checks in `appendPadding`
- Fails with the following error:
```
31 observations from 2023-02-28 11:06:24.702+0000 to 2023-02-28 11:06:24.746+0000 for: …
```

Padding g.t. maxMessageLength replay issue

---

aeron-driver/src/main/c/aeron_driver.c

If you try to start a C Media Driver with an existing directory, but without a CnC file inside, it will fail:
```
ERROR: driver init (2) (2) No such file or directory
[aeron_open_file_rw, aeron_fileutil.c:428] Failed to open file: /dev/shm/empty/cnc.dat
[aeron_driver_init, aeron_driver.c:860] could not recreate aeron dir: /dev/shm/empty
ERROR: driver close (22) (22) Invalid argument
[aeron_driver_close, aeron_driver.c:1117] driver is null
```
It's not really an error, could be due to the directory being empty, so it seems better to continue.
This aligns behaviour with the Java Media Driver.

[C] Do not fail if Aeron dir exists, but the CnC file does not.

---

aeron-driver/src/main/c/CMakeLists.txt
aeron-driver/src/main/c/aeron_driver.c
aeron-driver/src/main/c/aeron_driver_context.c
aeron-driver/src/main/c/aeron_driver_context.h
aeron-driver/src/main/c/aeron_port_manager.c
aeron-driver/src/main/c/aeron_port_manager.h
aeron-driver/src/main/c/aeronmd.h
aeron-driver/src/main/c/media/aeron_receive_destination.c
aeron-driver/src/main/c/media/aeron_receive_destination.h
aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c
aeron-driver/src/main/c/media/aeron_send_channel_endpoint.h
aeron-driver/src/test/c/CMakeLists.txt
aeron-driver/src/test/c/aeron_port_manager_test.cpp
aeron-system-tests/src/test/java/io/aeron/WildcardPortManagerSystemTest.java
aeron-test-support/src/main/java/io/aeron/test/driver/CTestMediaDriver.java
config/checkstyle/checkstyle.xml

Todd ported the port manager to C and I added some tests and small fixes on top.

C port manager

---

aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java
aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java
aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
aeron-driver/src/test/java/io/aeron/driver/IpcPublicationTest.java
aeron-driver/src/test/java/io/aeron/driver/UntetheredSubscriptionTest.java

This ports to the Java media driver the following change: 128ccb68e ("[C]: update pub-pos when updating pub-lmt.")

[Java] Update pub-pos when updating pub-lmt.

---

aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java
aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackupAgent.java
aeron-cluster/src/test/java/io/aeron/cluster/ClusterBackupAgentTest.java
aeron-system-tests/src/test/java/io/aeron/cluster/ClusterBackupTest.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestBackupNode.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestCluster.java

Where it will search for the most recent snapshot position less than or equal to the specified position. Only affects the first time the backup starts replicating from the cluster.

Have cluster backup start from a specific position

---

aeron-client/src/main/c/uri/aeron_uri.c
aeron-client/src/main/c/uri/aeron_uri.h
aeron-client/src/main/cpp/ChannelUri.h
aeron-client/src/main/cpp/ChannelUriStringBuilder.h
aeron-client/src/main/cpp_wrapper/ChannelUri.h
aeron-client/src/main/cpp_wrapper/ChannelUriStringBuilder.h
aeron-client/src/main/java/io/aeron/ChannelUriStringBuilder.java
aeron-client/src/main/java/io/aeron/CommonContext.java
aeron-client/src/test/cpp/ChannelUriStringBuilderTest.cpp
aeron-client/src/test/java/io/aeron/ChannelUriStringBuilderTest.java
aeron-driver/src/main/c/aeron_ipc_publication.c
aeron-driver/src/main/c/aeron_ipc_publication.h
aeron-driver/src/main/c/aeron_network_publication.c
aeron-driver/src/main/c/aeron_network_publication.h
aeron-driver/src/main/c/aeron_publication_image.c
aeron-driver/src/main/c/aeron_publication_image.h
aeron-driver/src/main/c/uri/aeron_driver_uri.c
aeron-driver/src/main/c/uri/aeron_driver_uri.h
aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java
aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
aeron-driver/src/main/java/io/aeron/driver/PublicationImage.java
aeron-driver/src/main/java/io/aeron/driver/PublicationParams.java
aeron-driver/src/test/java/io/aeron/driver/UntetheredSubscriptionTest.java
aeron-system-tests/src/test/java/io/aeron/UntetheredSubscriptionTest.java

* Additional refactoring/cleanup of C++ ChannelUriStringBuilder.

Add per channel untethered window limit and resting timeouts

---

aeron-driver/src/main/c/aeron_network_publication.c
aeron-driver/src/main/c/aeron_network_publication.h
aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
aeron-driver/src/main/java/io/aeron/driver/ReceiverLivenessTracker.java
aeron-driver/src/test/java/io/aeron/driver/ReceiverLivenessTrackerTest.java
aeron-system-tests/src/test/java/io/aeron/SubscriberEndOfStreamTest.java
aeron-system-tests/src/test/java/io/aeron/cluster/ClusterTest.java
aeron-test-support/src/main/java/io/aeron/test/cluster/TestNode.java

Disconnect if all have responded with an EOS.

Track EOS for each connected receiver to the NetworkPublication

---

aeron-archive/src/main/java/io/aeron/archive/Archive.java
aeron-archive/src/main/java/io/aeron/archive/client/AeronArchive.java
aeron-cluster/src/main/java/io/aeron/cluster/ClusterBackup.java
aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceContainer.java

Added `isConcluded` method for each Context similar to `io.aeron.CommonContext#isConcluded`.

[Java] add helper method to determine if context is concluded

---

aeron-cluster/src/main/java/io/aeron/cluster/package-info.java

Commit 04c37022a593c1c77a256488f999a4f9e8777a8d moved the location of the schema file. This PR adjusts sources to changes.

[Java] Update schema reference

---

aeron-driver/src/main/c/aeron_driver_conductor.c
aeron-system-tests/src/test/java/io/aeron/driver/Issue1719Test.java

... when checking for matching spy subscriptions

[C] compare publication stream id with link stream id 

---

aeron-driver/src/main/c/aeron_driver_context.c
aeron-driver/src/main/c/aeronmd.h

[C] Adding setter methods for CPU affinity to media driver

---

aeron-agent/src/main/java/io/aeron/agent/ArchiveEventCode.java
aeron-agent/src/main/java/io/aeron/agent/ArchiveEventDissector.java
aeron-archive/src/main/java/io/aeron/archive/ControlResponseProxy.java
aeron-archive/src/main/java/io/aeron/archive/ControlSession.java
aeron-archive/src/main/resources/archive/aeron-archive-codecs.xml

Initial work for keep alive changes

Create new Ping message for archive client keepalive

---

aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModule.java
aeron-cluster/src/main/java/io/aeron/cluster/EgressPublisher.java
aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java
aeron-cluster/src/main/java/io/aeron/cluster/client/EgressPoller.java
aeron-cluster/src/main/resources/cluster/aeron-cluster-codecs.xml
aeron-cluster/src/test/java/io/aeron/cluster/client/AeronClusterAsyncConnectTest.java
aeron-cluster/src/test/java/io/aeron/cluster/client/AeronClusterTest.java

An implementation of https://github.com/aeron-io/aeron/pull/1791#discussion_r2072710182

[Java] Make cluster publish leader heartbeat timeout to clients.

---

aeron-client/src/main/java/io/aeron/ChannelUriStringBuilder.java
aeron-client/src/main/java/io/aeron/CommonContext.java
aeron-driver/src/main/java/io/aeron/driver/Configuration.java
aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java
aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java
aeron-driver/src/main/java/io/aeron/driver/PublicationParams.java
aeron-driver/src/test/java/io/aeron/driver/MediaDriverContextTest.java
aeron-driver/src/test/java/io/aeron/driver/PublicationParamsTest.java
aeron-driver/src/test/java/io/aeron/driver/UntetheredSubscriptionTest.java
aeron-system-tests/src/test/java/io/aeron/UntetheredSubscriptionTest.java

Adding a separate linger timeout for untethered subscriptions.  Code is in place.  Might need to re-order some things and add more tests.  also may need to adjust the description.

Add separate linger timeout for untethered subscriptions
